### ISSUE TITLE
Diagrams not scaling properly on mobile.

### ISSUE THREAD

**Issue by dh494** [ucam-cl-dtg/isaac-app#120]
When I view diagrams on mobile (Internet Explorer on Windows Phone) the diagrams are scaled in the x direction to the width of the screen, but the aspect ratio is not constant; the y direction does not scale.

**Comment by alistairstead3408** [comment]
This is an IE-specific issue resulting from the SVG files being specified without a viewbox property. 

https://css-tricks.com/scale-svg/
