### ISSUE TITLE
Testing Broken Links

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#287]
I tried using several crawlers to check for broken links, but as expected none of them could cope with the AngularJS nature of the pages.

I did look into Selenium, but it seemed way above my head. There were half a dozen reccomended programs for testing Angular sites, but I couldn't understand how to get them to test all links.

If someone manages to get it working; I'm happy to run it and fix the links - but I think I'd need a fair bit of help to get that far.

(Many sites linked to this: https://developers.google.com/webmasters/ajax-crawling/ when I was looking; it might be useful, you may already know it.)

**Comment by daviesian** [comment]
I believe James has now done this.

**Comment by jsharkey13** [comment]
I have now done this, and will run code occasionally to check no new errors introduced. The code can also only check Live pages, useful for consistency checking!
