### ISSUE TITLE
Print styles need reconsidering.

### ISSUE THREAD

**Issue by daviesian** [ucam-cl-dtg/isaac-app#326]

**Comment by alistairstead3408** [comment]
Have started working on this. Chrome provides a nice print emulator we can use to fix the issues with. However, right now It doesn't seem to be matching what's actually printed...that could be related to the browsers default printing template.

**Comment by alistairstead3408** [comment]
Have fixed most if not all of the printing issues. It is now possible to print questions with and without hints. I have also removed the excess so that there are no extra blank pages.
