### ISSUE TITLE
Warning not appearing in filter when no questions available on live

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#338]
No warning is appearing in Maths, Calculus:
Integration: level 6
Differentiation: level 3
Differential equations: level 6

nor in maths, geometry:
vectors: levels 1, 3, 4, 6
trigonometry: levels 5 and 6
shapes: all warnings appearing fine on this one

nor in algebra:
series: levels 4,5,6.

Some of these levels have unpublished questions, some don't exist.

**Comment by daviesian** [comment]
These warnings are hard coded. Updated, assuming those listed in this question are the definitive new ones.

**Comment by nh357** [comment]
Sorry, Ian. These warnings still don't appear on either live or staging for the following questions:

Maths, geometry:
* vectors: there are no questions and no warning for levels 1, 3, 4, 6
* Trig: there is a warning but there are questions in levels 1,2,3,4. In this case, the warning of no questions needs to be removed. There is no warning and no questions for levels 5 and 6. 

Maths, algebra:
* series: there is no warning and no questions for levels 4, 5, 6.

**Comment by jsharkey13** [comment]
This is something I fix now, and Heather and I have checked that all is correct at the moment!
