### ISSUE TITLE
Incorrect answers causing correct units to show up as incorrect

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#339]
If an incorrect answer is added to a question, then if someone enters it it will always mark both the value and the units as wrong, even if the unit is the unit for the correct answer. This could make people think that the unit is wrong too.

![image](https://cloud.githubusercontent.com/assets/6358545/5302417/099c2000-7bd8-11e4-9671-55e51f9c71e8.png)

**Comment by daviesian** [comment]
I believe this is by design.
