### ISSUE TITLE
Odd search behaviour

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#344]
For example, when searching for the problem "Bismar Scales", typing in "bis" won't find it, but "bismar" will. On the game builder this could confuse teachers when the expected question doesn't show up as the search updates.

**Comment by nh357** [comment]
If type pull, pull* or pull% into search field in game board builder or normal search it will come up with "similar" words such as: Product rule, Ball dropping onto spring, liquid pool, pulley system, etc
