### ISSUE TITLE
Unclear (to teachers) how to select questions in game builder

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#345]
I had searched for a question in the new game_guilder; questions appeared in the box labelled 'Search Results'; there's no instruction saying something like "click in the box to the left of the question to select it; you can choose up to ten questions".

Perhaps the text "Find questions to add to your new game board..." higher up on the page could be expanded to include a bit more guidance.

Cheers,
Ally

**Comment by sacummins** [comment]
Please review on https://dev.isaacphysics.org/game_builder and let me know if you are happy with the changes to the text. (You may need me to give you an upgraded account on dev for you to be able to see it)

**Comment by allydavies** [comment]
Yes, I think I need an upgraded account on dev.
I tried logging in with ally.davies@physics.org and it told me 'incorrect credentials'
