### ISSUE TITLE
Difficulties using "filter by concept", in choose your questions

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#348]
I was exploring how this works.
This is what I've found:
(a) if I type something that is not listed as a concept, the word appears in the box, but it doesn't actually do anything. I was actually trying to find questions with graphs in them, and typed "graph" which sat in the box, but didn't actually have any effect, and I didn't get any kind of message such as "'graph' isn't a concept you can filter on".
(b) if I start typing something that is a concept (or is in the title of a concept), then it's difficult for the user to see what is happening, e.g. I type "mass" in the concept filer box. On the screen appears the word "Centre" with a little + sign near it. I click the add sign and the concept "centre of mass" is added. So, could the box that appears be bigger, so you can see the full concept that is suggested to you before you add it? Could it be a drop down that as you type it takes you to a suggested concept?

**Comment by jsharkey13** [comment]
Part of (b) sounds like a re-run of the wonderful #186 which we thought had been fixed before . . .
