### ISSUE TITLE
Pod carousel does not pause if you don't leave the carousel area after clicking an arrow

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#351]
If you use one of the navigation arrows on the pod carousel and then leave your cursor inside the pod carousel, it will move automatically after a short time instead of pausing. 

Moving the cursor outside the pod and back in then gives the desired behaviour of pausing the carousel

**Comment by alistairstead3408** [comment]
Cannot reproduce. There is a 10 second delay between movements when the cursor is outside the carousel, and a pause when the cursor is inside. @mjc209 are you still seeing this problem? If so, which browser are you using?

**Comment by mjc209** [comment]
I'm still seeing this problem using Chrome, Version 41.0.2272.89 m

**Comment by alistairstead3408** [comment]
Fixed
