### ISSUE TITLE
Slow loading of maths on Safari and Chrome

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#352]
The maths is loading very slowly on Safari on both desktop and mobile and in Chrome for Desktop. If you refresh a page the maths appears or if you leave it alone a long time (~3-5 minutes) it will then appear. It also appears on the first page you go to on the site, but afterwards it struggles. The little grey box telling you what is happening on the bottom left-hand side of the page seems to flicker between Typesetting and  processing I think it says.

**Comment by daviesian** [comment]
Should be better now.
