### ISSUE TITLE
Share link doesn't work for this board I made

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#355]
I made this board (using the game board builder), but when I click on the share link, a thin green line appears (like the background of the normal share link) higher than the share link appears usually and I am unable to view any text.

https://isaacphysics.org/#88960fc6-c7a7-48d2-bbcf-c93d8a6bd5a2

**Comment by sacummins** [comment]
This appears to work for me when I try to share the board on the my boards page. Please reopen if it is still broken.

**Comment by mjc209** [comment]
I recall there being some discussion about this and it getting fixed, so hopefully it's fine now
