### ISSUE TITLE
Mathjax rendering in answers

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#359]
In a question, the units appear fine in the drop down menu, but once selected, the latex is displayed, e.g. $\units{m}$ and then the answer placed in the accordion bar appears as $\quantity{1.8}{m}$. If you refresh the page, the mathjax renders properly. 

airzooka is an example of a numeric question to test this with.

**Comment by daviesian** [comment]
Fixed in 38b0a88d280fbc92bc8886407ff1eac4e1895f76.
