### ISSUE TITLE
Toast Notification appears to block elements when invisible

### ISSUE THREAD

**Issue by sacummins** [ucam-cl-dtg/isaac-app#362]
1. Go to https://dev.isaacphysics.org/admin/stats as an admin or staff user.
2. Click 'show school data'.
3. Now attempt to click the first school URN in the list to view that schools user list. (If you inspect the element you will find it is the toast notification that is preventing the click event).

![image](https://cloud.githubusercontent.com/assets/5736542/6551718/0fd19c46-c635-11e4-826b-a90ac976d2c2.png)

**Comment by daviesian** [comment]
Fixed in ab12dea62f10f1d33eb8607c22479aed52d4e16c.
