### ISSUE TITLE
superscripts in answer box

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#364]
I thought this had already been raised but couldn't find it when I searched for it. 
In an answer box, if you type 7.9x10^-7 it is marked as correct, but if you write it as 7.9x10^(-7) it is marked as wrong. Could both be possible? Or can one of the examples have a negative exponent in there to show how to input it. 
Also, could the answer that is displayed in the accordion be "proper maths"? The times symbol appears as an "x" and only the minus sign is raised. The problem in question is https://staging.isaacphysics.org/questions/ch_b_p6 partA
![superscripts in answers](https://cloud.githubusercontent.com/assets/5849827/6619456/38c8a92a-c8c2-11e4-98cf-77a7b2279040.jpg)

**Comment by jsharkey13** [comment]
#411 is related to this

**Comment by jsharkey13** [comment]
I think this was fixed when I moved to a better way of matching exponents. See [these lines](https://github.com/ucam-cl-dtg/isaac-api/blob/6baccbadf0ecc6f0a8595d3ca22b18dcf8190667/src/main/java/uk/ac/cam/cl/dtg/isaac/quiz/IsaacNumericValidator.java#L41-L45) of the numeric checking code for the regex used to extract the exponent now.
