### ISSUE TITLE
Logic for hexagon display

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#368]
I need to check my thinking on this one but I am using "Bed of Nails" as a test case.  There are 3 parts to the question.

When I have 1 part right and haven't attempted the other two it says "Well done" where as I think it should say "in progress"?

When I have 1 right and 1 wrong it still says well done where I think it should say "in progress" - because I can get it right but haven't finished as yet.

If I have done 2 parts correctly it says perfect rather than well done.

If I get 2 parts wrong it does say try again :)

**Comment by jsharkey13** [comment]
I think this was fixed a long time ago . . .
