### ISSUE TITLE
"View board" not displaying properly in Safari

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#369]
In Safari (8.0.4), under assignment progress, the "view board" text on the accordion is not on the same line. The "view" is a bit lower than the "board". Fine in Chrome. 
![view board](https://cloud.githubusercontent.com/assets/5849827/6828483/ffa38568-d305-11e4-951e-a401419b70ec.jpg)

**Comment by jsharkey13** [comment]
This has changed to "View Assignment" I think, on the student page:
![image](https://cloud.githubusercontent.com/assets/8060558/10843249/df89b1f8-7eef-11e5-810b-bacb31d49d6c.png)
(which is still a little out of alignment)

but has been replaced with "View Mark Sheet" for teachers which gets rid of that image and so fixes the alignment issue above.

**Comment by alistairstead3408** [comment]
Appears to be fixed.
