### ISSUE TITLE
MathJax rendering latency

### ISSUE THREAD

**Issue by arnaudbenard** [ucam-cl-dtg/isaac-app#374]
Hi,

I have noticed that there's a latency for LaTeX rendering on the front-end. For example, It takes a few hundred ms on Chrome to render the formulas on this page: https://isaacphysics.org/concepts/cp_equilibrium .

The [KaTeX library](http://khan.github.io/KaTeX/) seems to render faster than MathJax. I don't know how much work it would take to replace the library, but it would make the UX nicer. ;)

Cheers!

**Comment by sacummins** [comment]
Hi,

Thanks for the feedback. 

We had noticed the annoying latency too. Moving to KaTeX is on the plan eventually (in fact a new component that is being developed for the site is already using it and will go live in the not to distant future).

For now we will use this issue to track our progress.

Thanks again,

Steve

**Comment by arnaudbenard** [comment]
Awesome! :+1:

**Comment by jsharkey13** [comment]
We updated to MathJax 2.6 recently, and this has a pre-rendering render that replaces the old `----` bars that used to show up when loading was slow. I think we can live with this, and KaTeX is being used in some places where it's helpful.

**Comment by jsharkey13** [comment]
Thank you for the feedback, and the suggestion to use KaTeX!
