### ISSUE TITLE
Clicking "Save this board" does not do what I would expect

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#377]
If I create a board using the filter and then click on "Save this Board" I get directed to Assign a Board, when logged in as an admin and as a teacher. If logged in as a student or content editor then it takes you to the my board pages.

**Comment by nh357** [comment]
It does also save it to my boards when logged in as admin or teacher.

**Comment by nh357** [comment]
Having worked through the regression test, realise that this is normal behaviour.

**Comment by nh357** [comment]
Sorry for the indecision. Having spoken with Lisa about the different behaviours, it would be good to make them all consistent. Currently:
1.As a teacher:
Click on board title: title box appears with Save and Cancel button underneath. Hit save, you remain on the page with the board and it appears in your boards. 
Click on Save this board: Board appears in My boards and I get directed to the Assign this board page
Click on Add this board from Top Boards: Board appears in my boards and you get redirected to the Assign this board page

2. As a student: 
Click on board title: title box appears with Save and Cancel button underneath. Hit save, you remain on the page with the board and it appears in your boards. 
Click on Save this board: Board appears in My boards and I get redirected to the My boards page. 
Click on Add this board from Top Boards: Board appears in my boards and you get redirected to the My Boards page.

Suggestion:
Remove the ability to save a board by clicking on the title and instead, if click on Save this board, have dialogue box to change the title appear around the title with the Save and Cancel button below it. If a teacher, when you hit save it takes you to the assign this board page, if a student, it takes you to My Boards page. 
If add board from Top Boards page, then leave current behaviour.

**Comment by sacummins** [comment]
Renamed to "Add to my boards"
