### ISSUE TITLE
Printing question with correct answer

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#378]
If printing a question which has answers in the accordions, then these answers appear cut off on the bottom. This occurs on both Safari and Chrome on a mac. 
![printed question](https://cloud.githubusercontent.com/assets/5849827/7026299/e0efa706-dd40-11e4-9d04-2b7fe140fca4.jpg)

**Comment by alistairstead3408** [comment]
The fix for issue #371 removes printing for correct and incorrect labels.
