### ISSUE TITLE
Create a specific link to pre-fill the board builder to show book questions

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#380]
To enable teachers to create their own combination of pages from the book could we have a specific link that prefills the search on the board builder with "book" and "any level"  so that only the book questions are shown.

I will then include this link on the book page.

**Comment by ljw21** [comment]
Could we also have the results order by title so that it looks like

A1 xxxxx
A2 xxxx
A3 xxxx

**Comment by sacummins** [comment]
So now you can use links of the form /game_builder?query=book&subject=physics&level=any&sort=title

**Comment by allydavies** [comment]
I think this will be a very useful tool for teachers.
Could this list appear in chapter number order? i.e. I'd like to enter
"book" in the search box, click "any level" in the level filter, and then
see in the list of "questions" A1, A2, A3, A4, ...
Then it would be easy to find any particular chapter a teacher might be
looking for.

Currently, it appears in an order that makes it rather difficult to find
any particular chapter (apart from those at the top of the list).

Cheers,
Ally

Mr Ally Davies
Hub Events Manager, Isaac Physics <http://www.isaacphysics.org>

Cavendish Laboratory
Cambridge University
J J Thomson Avenue
Cambridge
CB3 0HE
Tel: 01223 747036

Email: ally@isaacphysics.org
Webpage: http://isaacphysics.org
