### ISSUE TITLE
Back button in browser not taking you back to the book page from the set_assignments page.

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#382]
Go to
https://isaacphysics.org/physics_skills_14

Click on an accordion and a page within it to "add to my boards".

This then takes you to set assignments :)

The problem is that the back button of the browser does not then take you back to https://isaacphysics.org/physics_skills_14 if you want to assign a different set of questions to a different group.

I.e. to get back to the book index page you have to type the URL again.

**Comment by nh357** [comment]
This is also true from My Boards. 

I also noticed that the back button does work for both Assign a Board and My Boards page when you didn't get to it by pressing Save or Add to my boards.
