### ISSUE TITLE
suggestion to improve ease of entering text in boxes

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#387]
1. Manage Groups
Would be good to add some 'background text' to the 'create group' box, something like:
"Enter the name of your group here"
Would be like the "Enter your code in here" text on the 'My Account' page to link with teachers

2. Gameboard Builder
In the 'Game board title' box, the text "Game board title" appears, but you have to highlight it and replace it, whereas the text to the left "Id (optional..." is just background - wherever you click within the box, the cursor appears at the left of the box.

Cheers,
Ally

**Comment by ljw21** [comment]
Dear Ally,

 

In answer to 2.  The difference is because a title is necessary an id is not.

 

Lisa

**Comment by allydavies** [comment]
Sorry, for 2 I realise I didn't actually suggest what I'd like:

I'm suggesting that the prompt text in the right hand box (the game board
title) should be formatted exactly as the "Enter your code in here" is, and
then the teacher would just click anywhere in the box and type, rather than
click and find they're typing in the middle of the text that was there
telling them what to do.
Cheers
Ally


Mr Ally Davies
Hub Events Manager, Isaac Physics <http://www.isaacphysics.org>

Cavendish Laboratory
Cambridge University
J J Thomson Avenue
Cambridge
CB3 0HE
Tel: 01223 747036

Email: ally@isaacphysics.org
Webpage: http://isaacphysics.org
