### ISSUE TITLE
When you have the incorrect role an error page should be displayed.

### ISSUE THREAD

**Issue by sacummins** [ucam-cl-dtg/isaac-app#388]
If a user gets demoted for some reason and has a favourited link to the admin page there is just an error in the console and no indication that something went wrong. The page contents does not update either.

![image](https://cloud.githubusercontent.com/assets/5736542/7088786/8f410f8a-df8e-11e4-95fc-630468222af4.png)

**Comment by daviesian** [comment]
Fixed in 5a043ad7e05c544d57bd04aa7b57f5652de3dda3.
