### ISSUE TITLE
Alignment of numbers in nuclear equations

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#395]
Board J1 from the Physics Skills book uses nuclear equations.  At the moment the atomic/mass numbers are aligned left which looks a bit odd, especially for an electron with numbers 0, -1.  Can these be aligned right?

**Comment by daviesian** [comment]
This is a content issue. You should specify atomic/mass numbers using the [mhchem package](http://mirror.unl.edu/ctan/macros/latex/contrib/mhchem/mhchem.pdf) like so:

`\ce{^{241}_{95}Am}`
