### ISSUE TITLE
grouping of zeros

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#396]
Has there been discussion of whether zeros are grouped?
Some numbers are a little difficult to read on screen e.g. in https://isaacphysics.org/questions/ch_a_p3?board=physicsskills_book_ch_a3
Qu 3.8 shows the number 0.000005638

Can this easily be rendered as "0.000 005 638"?

http://www.npl.co.uk/reference/measurement-units/si-conventions/
Suggests that this is absolutely standard, but of course that doesn't make it trivial to do!

**Comment by sacummins** [comment]
This is a content issue. You are able to control the text in questions via the editor.
