### ISSUE TITLE
indication that school data and garboard data has loaded

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#397]
On a small screen, you do not see the beyond the "statistics at a glance" box when scrolled all the way up. So when you click on School data, you don't actually realise that it has loaded below the "statistics at a glance" box. Would it be possible to make the page automatically scroll down to the new box? I initially thought nothing had happened, until I happened to scroll down.

**Comment by sacummins** [comment]
Global loading icon should hopefully now have fixed that.
