### ISSUE TITLE
Numbers not appearing when Figures are referenced

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#398]
For example on staging.isaacphysics.org/concepts/cp_fields there are no numbers on references to figures.

![image](https://cloud.githubusercontent.com/assets/6358545/7136812/30cb089a-e2ac-11e4-8f79-015e9108a40a.png)

This occurs in Chrome and Firefox on Windows 7

**Comment by jsharkey13** [comment]
This was fixed in https://github.com/ucam-cl-dtg/isaac-app/commit/dd7937291b85513926e84007c53550a93e3db647
