### ISSUE TITLE
Question not recognising that answers have been marked as correct

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#400]
In https://staging.isaacphysics.org/questions/Balancing_Forces_on_an_Electron?board=4577c932-c8b7-4cba-aa91-63260efcf9ae although all parts have been answered correctly on going back to the board the question is showing as In Progress.

Going back to the question page shows that the answer is correct but it doesn't appear in the accordion title as it normally does.

![image](https://cloud.githubusercontent.com/assets/6358545/7140633/49d9c9d0-e2c4-11e4-8aeb-2948155626f6.png)

**Comment by jsharkey13** [comment]
This got broken ages back, fixed, and has since been removed for a while. We could bring it back, but it's complicated!
