### ISSUE TITLE
'Administrative Tools' sometimes doesn't appear

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#404]
when you are in site admin, and you have done something e.g. search for an account, sometimes the 'administrative tools' box doesn't reappear; you can get it back by going somewhere other than site admin and then coming back via the menu.
An example sequence is:
MENU, site admin, enter a family name to find user, click on the profile you're interested in.
Then if you click back (or if you go menu site admin again), the page appears showing the Useful Links box, but without the 'administrative tools'

**Comment by sacummins** [comment]
This should hopefully now not be a problem as a result of the change in 1feeb8526ead2baea577256995e8bd9fd45d403f
