### ISSUE TITLE
Add two more items to Menu->Helpful Information

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#405]
A request to split 'Problem Solving Guide' into three seperate pages:

*Problem Solving Guide
*Sig Fig and Conventions
*Data, Formulae and Units

I have created the two additional pages and these are ready to go live:
conventions.json
data_formulae_units.json

However, i will need to edit the Problem Solving Guide page to remove the info that has been moved onto these seperate pages. 

I suggest that these two pages are made accessible from the MENU.

**Comment by hjp22** [comment]
REQUEST CHANGED:
Can the menu item be changed from 'Problem Solving Guide' to 'Solving Problems on Isaac'

**Comment by sacummins** [comment]
I believe this has not yet been actioned due to text wrapping issues with the suggested title.

**Comment by sacummins** [comment]
All of these menu items will be changing with the new homepage design. So I will close this issue for now until we have completed the work required for the homepage.
