### ISSUE TITLE
Live site; only first character of exponent appears as superscript in Isaac quoted answer

### ISSUE THREAD

**Issue by rh584** [ucam-cl-dtg/isaac-app#411]
![image](https://cloud.githubusercontent.com/assets/7080579/7317849/5287e52e-ea7d-11e4-81b1-06e41ff9950f.png)
Q:H1 Uniform Electric Fields
When question is fully answered, Isaac has a summary of the answers and the superscript exponents are only superscript in the first character.

**Comment by jsharkey13** [comment]
We got rid of this accordion answer preview because people added more than one question to an accordion section and it broke. So this is no longer an issue.
