### ISSUE TITLE
Statistics - Users at a school

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#413]
When you click on the URN link you get a list of users at that school.  It would be really useful for the email addresses to be included in that list.

**Comment by sacummins** [comment]
We will be providing functionality for staff to email various user groups either by school or role in the near future.

**Comment by hjp22** [comment]
Where we don't yet have functionality to automatically email user groups, it would be useful to see the following:

Show School Data
Click URN link -> List of all users at that school are shown in a table with the following columns: 
Name / Role / Gender / Reg Date / Last Seen

Could an 'Email' column be added here: 
We can then easily copy the email addresses for every student / teacher registered at a school and send them an alert that a workshop is running nearby.

**Comment by allydavies** [comment]
This page now shows the list of users etc, but it would be useful to have the NAME of the SCHOOL on the same page

**Comment by jsharkey13** [comment]
So this is fixed; admins/event managers can search for users by school url and admins can then email them if necessary. The school page shows the current school too!
