### ISSUE TITLE
"Next question" box appears at the top of the page

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#419]
When a question is answered, there's now a box which offers congratulations and a button to click to go to the "next" question in the board. However this always appears at the top of the page regardless of how far down the user has scrolled to get to the final part of the question, so it can appear off the top of the screen. This is bad, especially as when it opens it "greys out" the rest of the page so that it can't be clicked.

**Comment by alistairstead3408** [comment]
The popups were being triggered depending on the percentage completeness of the gameboard, which was calculated using the number of passed/perfect questions / total questions on the board. This issue resulted from reaching the passmark, and the gameboard containing only one question.

**Comment by alistairstead3408** [comment]
@mjc209 is there a time when this popup appears and you can't see it? Or do you just dislike the fact it scrolls to the top of the page?

**Comment by mjc209** [comment]
The page didn't always scroll, so sometimes I couldn't see the popup
