### ISSUE TITLE
Loading icon not disappearing

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#420]
When loading some gameboards the loading icon remains even after the board has loaded. Then if you go to another page that takes some time to load you end up with two loading icons.

![image](https://cloud.githubusercontent.com/assets/6358545/7513743/62e259f0-f4ae-11e4-8c08-7f145ab85661.png)

**Comment by mjc209** [comment]
This appears to happen either when I create a board using the gameboard builder or when I open a board from My Boards or Assign a Board

**Comment by mjc209** [comment]
I also tried to get to the assignments page when not logged in and the loading icon appeared on top of the login page

**Comment by mjc209** [comment]
Also when logged in as a student and attempting to open (via URL) the "Manage Groups" page

**Comment by mjc209** [comment]
This occurs on Chrome on both desktop and Android

**Comment by mjc209** [comment]
This bug doesn't appear in previous situations anymore, but still occurs when a board is deleted from the My Boards page

**Comment by sacummins** [comment]
Fixed in 8dc2f1c007818a5a96b421168f414bcbe16bcbd0
