### ISSUE TITLE
Option to NOT randomly order multiple choice answers

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#422]
Some questions require the user to select the correct answer, A, B, C or D.  In this instance it is confusing if these answers are ordered randomly.  Could a feature be added in the editor to allow the content writer select for the multiple choice answers to not be reordered?

**Comment by jsharkey13** [comment]
I do remember we had a long discussion about this when we added the first A/B/C/D/E choice questions; but I think we decided we had other priorities then.
(It was because we changed things in #69 that it later became an issue.)

Also; editor stuff might be best under scooter, not isaac-app.

**Comment by jsharkey13** [comment]
I added this functionality in https://github.com/ucam-cl-dtg/isaac-api/commit/804db7f2e48b627d57eaa00a032a4397e6655190 but it's not been added to the editor. It is now possible to add the line:
`"randomlyOrderChoices": false,` to the JSON of the `isaacMultiChoiceQuestion` to keep the choices in the order they are entered in.

**Comment by allydavies** [comment]
Hi James,

I tried this method, (on Wax_prism), by simply ADDING this line (maybe in a
bad place?)

"randomlyOrderChoices": false,

to the json, but it didn't work.

I then tried editing the line that previously said:

"randomiseChoices": true

to become

"randomiseChoices": false

This DID work.

If your suggested line is NOT the right one, what's the best way to inform
everyone? Should I reopen the github issue, comment and close it?

Cheers,
Ally

Mr Ally Davies
Hub Events Manager, Isaac Physics <http://www.isaacphysics.org>

Cavendish Laboratory
Cambridge University
J J Thomson Avenue
Cambridge
CB3 0HE
Tel: 01223 747036

Email: ally@isaacphysics.org
Twitter: @isaacphysics <https://twitter.com/isaacphysics>
Webpage: http://isaacphysics.org

**Comment by jsharkey13** [comment]
There's a button in the editor to do this now, and there has been for a week or two. You might have an old version cached which doesn't have this button, but clearing your cache and refreshing should fix that.

You're looking at the oldest comment in the thread, the name got changed after that to the one you found that works.
