### ISSUE TITLE
"Next Question" box appears after completing Part A

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#423]
"Next Question" box appears after completing Part A, B, C etc, instead of just when all parts have been completed.  
Happened for this question:
https://staging.isaacphysics.org/questions/basic_flux_linkage?board=ff86c1ec-707c-4824-90c7-06cc04186a4b

**Comment by alistairstead3408** [comment]
I can't reproduce this. Is it still happening?

**Comment by jsharkey13** [comment]
It's not happening any more; we seem to have disabled the question (but not board) completion pop up.
