### ISSUE TITLE
Keep getting completed message on book pages after reaching mastery level

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#431]
Once you have successful reached the mastery score, you get a pop-up telling you that you've completed the page. This pops up again every time you successfully complete another part of the question on the page, which is annoying

**Comment by alistairstead3408** [comment]
The popups were being triggered depending on the percentage completeness of the gameboard, which was calculated using the number of passed/perfect questions / total questions on the board. This issue resulted from reaching the passmark, and the gameboard containing only one question.
