### ISSUE TITLE
tooltip inconsistent and text change

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#433]
![image](https://cloud.githubusercontent.com/assets/5931508/8055979/c8cba3f0-0e9b-11e5-9cc7-2f28fbe1fc05.png)

Tool tip disgarees with the number of groups assigned to board

New wording of tooltip = "This board has been assigned to $$$$,$$$$, $$$$ (names) groups

**Comment by daviesian** [comment]
This is already done, but the tooltip does not get updated until the page reloads. So, the issue becomes:

* Update the tooltip when assignments change.

**Comment by daviesian** [comment]
The tooltip also does not get initialised properly on initial page load.

Load the page, and the tooltip is wrong. Navigate to a different page, navigate back, tooltip is correct.
