### ISSUE TITLE
OwlCarousel - Uncaught Type Error

### ISSUE THREAD

**Issue by sacummins** [ucam-cl-dtg/isaac-app#434]
After loading the homepage fully (with dev tools open), navigate to any other page for example a question page or the admin stats page.

After a 10 seconds you will see a number of the following errors raised (it appears to be on a recurring timer)

Uncaught TypeError: Cannot read property 'indexAbs' of undefinedOwl.minimum @ owl.carousel.js:1453Owl.normalize @ owl.carousel.js:1410Navigation.getPosition @ owl.carousel.js:3071Navigation.next @ owl.carousel.js:3084jQuery.extend.proxy.proxy @ jquery.js:513Autoplay.play @ owl.carousel.js:2700(anonymous function) @ owl.carousel.js:2669jQuery.extend.proxy.proxy @ jquery.js:513

![image](https://cloud.githubusercontent.com/assets/5736542/8062363/357c8aa2-0ec7-11e5-8f38-18aac76d1fde.png)

**Comment by alistairstead3408** [comment]
Fixed - it was a problem with destroy not being called correctly. The fixed caused another issue, which has been raised in #435
