### ISSUE TITLE
Getting to Assign a board to delete an assignment

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#436]
I wanted to delete a group from an assignment and with the new global nav "set assignments" takes you to the teacher features with a modal.  I then have to click "set one of my boards" so that I can delete a group from a board I already have.

Need a way of getting to assign a board

**Comment by sacummins** [comment]
Where shall we put a link? Maybe in assignment progress at the top? or the teacher features page?

**Comment by sacummins** [comment]
Fixed in 71e6d857c6d5bcc2be484c13783ba9c86b26ba55
