### ISSUE TITLE
improvement to Contact us page

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#437]
The contact us page has some text that is a relic from when there was no events page:
Upcoming events
If you'd like to find out more about our monthly upcoming events please drop us a mail at
events@isaacphysics.org

Would be better to get rid of this section completely.

**Comment by sacummins** [comment]
Rather than removing it I have added a link to the events page.

The text now reads: "Upcoming events
If you'd like to find out more about our upcoming events visit our
events page."

This change will be visible on dev shortly.
