### ISSUE TITLE
Teacher Features modal is missing link to teacher forum

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#441]
When Lisa first showed the teacher features modal last week, there was a link to our talkphysics teacher forum.
This link isn't present in the live version and there is IMHO no other sensible place to have this link.
Not sure if this is an oversight or a policy decision. Either way, I think the forum link is really important and would best be placed here.

**Comment by sacummins** [comment]
Closed in 2dbfefeb828edac76cac5058352c1cb3efe48d4e
