### ISSUE TITLE
Angular Sign up Error 

### ISSUE THREAD

**Issue by alistairstead3408** [ucam-cl-dtg/isaac-app#442]
When signing up and clicking "register now", all fields go blank and warning errors appear before loading to the next page.  

![registration-angular-delay](https://cloud.githubusercontent.com/assets/810221/8281332/bcee1e94-18de-11e5-8f26-28930c7d7873.png)

**Comment by sacummins** [comment]
This appears to have fixed itself - reopen if it is still an issue.
