### ISSUE TITLE
Latex multi line rendering error

### ISSUE THREAD

**Issue by ss2165** [ucam-cl-dtg/isaac-app#445]
https://staging.isaacphysics.org/questions/flying_off_earth

Fraction on subsequent line causes uneven rendering on F= ma:

![image](https://cloud.githubusercontent.com/assets/12997250/8302727/98d4080e-1990-11e5-95b0-a8063880c5c7.png)

**Comment by ss2165** [comment]
This issue appears to be repeatedly occurring for rendering of newton's second law.

**Comment by daviesian** [comment]
This is a MathJax issue, closing because it will go away when we switch to Katex.
