### ISSUE TITLE
No hints on "show answer" questions

### ISSUE THREAD

**Issue by ss2165** [ucam-cl-dtg/isaac-app#446]
Hints are written on editor but do not seem to appear for "Show Answer" type questions 

https://staging.isaacphysics.org/questions/Balancing_Forces_on_an_Electron
![image](https://cloud.githubusercontent.com/assets/12997250/8327060/7bae0996-1a5d-11e5-84fd-8a959c93eaff.png)

https://staging.isaacphysics.org/questions/oil_drop_multiple_fields_num
![image](https://cloud.githubusercontent.com/assets/12997250/8327077/96fe0ca0-1a5d-11e5-9cc9-f78c2bafc9a0.png)

**Comment by daviesian** [comment]
QuickQuestions were never supposed to have hints. This would be a new question type, which can go on the backlog if required.
