### ISSUE TITLE
Back button doesn't do anything

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#449]
On this page:
https://isaacphysics.org/concepts/cm_vectors
there's a back button.

I arrived here via 'open in new tab'. The button is still there and looks like it should do something, but (of course) is doesn't do anything.

Should it appear greyed out? Perhaps works the same on all concept pages? Do other websites get around this, but just NOT doing back links, and just relying on the browser back button?

**Comment by alistairstead3408** [comment]
Would you rather the button stayed visible, but read '<- All concepts' or it be not visible?

**Comment by alistairstead3408** [comment]
Just spoken to @sacummins about this and we think if you land on that page from the concepts page then there should be no back button, but if you arrive from a question then there should be. What do you think @allydavies?

**Comment by alistairstead3408** [comment]
@allydavies any thoughts?

**Comment by allydavies** [comment]
So then, if you have the question open in one tab, and you open the concept in the new tab, clicking back would do what:
1. close that tab and take you back to your open question tab?
2. open your question in this second tab (might that be confusing?, two tabs open with the same question)
I'd prefer option 1 (or to not have the back button even if you've come there from a question).

**Comment by alistairstead3408** [comment]
Closing the tab and taking you back to another tab isn't technically possible - at least in a way that makes sense for the user experience. We also can't really change the behaviour if users open a link in a new tab vs. navigating there from a page in the same tab.  
 
In a situation where the user navigates to that page from the concepts list, I'm suggesting that the "back" text should be changed to "all concepts". That way, if you opened a concepts tab, you would see an "all concepts" button, which I think would make sense. If they navigate there from a question, it should say "back to question". They can choose if they use that link to go back to their question, or close the tab themselves to get back to the previous tab.

**Comment by allydavies** [comment]
Yes that's fine. Thank you.
