### ISSUE TITLE
Diagrams in post-correct answer text not appearing

### ISSUE THREAD

**Issue by rjgs2** [ucam-cl-dtg/isaac-app#450]
When a diagram is in the text/figure which appears after a correct answer in a question (both multi choice and numerical) when you click check my answer, nothing comes up (not even the correct sign).

https://staging.isaacphysics.org/questions/latticework - Physics, Chemphysics, Thermo, Level 4
http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/questions/physics/chemphysics/thermo/level4/latticework.json

and

Part 2 of

https://staging.isaacphysics.org/questions/catalyst - Physics, Chemphysics, Kinetics, Level 4
http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/questions/physics/chemphysics/kinetics/level4/catalyst.json

**Comment by daviesian** [comment]
To reproduce:

* Go to /questions/catalyst
* Answer "MnO2" for part B
* Notice that nothing happens. There was a `500` on the server.
