### ISSUE TITLE
Sig fig text goes red when actually have given wrong numerical value.

### ISSUE THREAD

**Issue by mw141** [ucam-cl-dtg/isaac-app#451]
I would prefer the red to just be around the number box and not on the box containing the words "Please answer to an appropriate number of significant figures." if in fact one is wrong from having entered the wrong number.
If anything, the "Check your working" should be red when it comes up for guidance.

**Comment by sacummins** [comment]
Fixed in 8735e461bdc485fd52835a0685e60dd55a435519
