### ISSUE TITLE
Booking teachers onto events through event admin

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#454]
Have successfully updated the list for Cambridge June 2014 but can't book anyone onto Altrincham 24-10-14?

Lisa

**Comment by ljw21** [comment]
When I click on book on event (next to a name) nothing happens.

**Comment by sacummins** [comment]
Relates to an api database error (which unhelpfully is never logged). Added logging in ucam-cl-dtg/isaac-api@ab1b294aa6a53feacda3185af2cd994808578827 to help investigate the problem

**Comment by sacummins** [comment]
Fixed. This error was as a result of postgres getting confused as to which number is next for the auto increment (SERIAL) ID. Weird.
