### ISSUE TITLE
Change school set column to "school" in admin page

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#455]
Would liek to see name of school rather than school set YES on admin page.

**Comment by allydavies** [comment]
This is becoming more important - e.g. to help us to work with teachers, and to identify 'lone wolves' those students working without a teacher in their school / college.

**Comment by jsharkey13** [comment]
This is extraordinarily difficult, but school URN is now available as hover text when "School Set" is "Yes" as per https://github.com/ucam-cl-dtg/isaac-app/commit/c04150e3e69e23a7a14a6af77f2409804778bd4c, which seems a useful compromise.
