### ISSUE TITLE
mhchem package for MathJax

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#464]
Could you add the mhchem package to the tech install? Thanks.

**Comment by sacummins** [comment]
What do you mean by tech install?

mhchem is already installed on isaac-app (5a043ad7e05c544d57bd04aa7b57f5652de3dda3) and the editor (ucam-cl-dtg/scooter@166936d3b298a293d4ddd2e573cadc3489ce5f38):

**Comment by mjc209** [comment]
Sorry, I meant tex. And that's good, I'll pass that on.
