### ISSUE TITLE
Logging in sends you back to the front page

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#465]
When you log in you always end up back on the front page, looking at your most recent board. Is there a way that people could be returned to the last page that they were on before logging in?

**Comment by mjc209** [comment]
Any news on this?

**Comment by jsharkey13** [comment]
I'll need to talk to @daviesian.

The code below 'fixes' it, but I'm hesitant to do it because I don't really understand Angular's routing business. There was also talk a while back about a related problem and it was too hard to solve.

```html
<a id="login-tab" ng-if='!user._id' class='ru-desktop-nav-item'
  ui-sref="login({target: $root.relativeCanonicalUrl=='/' ? null : $root.relativeCanonicalUrl})">
```

**Comment by sacummins** [comment]
This appears to have been fixed for some time. Closing
