### ISSUE TITLE
Deleting an Assigned Board

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#466]
See https://github.com/ucam-cl-dtg/rutherford-content/issues/322

>At the moment a teacher can delete a board in My Boards that they have assigned to a class as homework. I don't think this should be allowed. Or if it is allowed, a warning should pop up saying 'Unassign from class #?'. Otherwise you get the situation where the students can see they have homework but the teacher has no record of it on their account.

**Comment by sacummins** [comment]
I suppose we could prevent users from deleting a board on the set assignments screen until they have unassigned all groups?
