### ISSUE TITLE
Board getting lost if you click too quickly

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#468]
If, after completing a question you click Back to Board before the pop up for completing the question appears, you end up getting dumped back at a random board, with the pop-up popping up later with variables inside rather than the correct board and question:

![image](https://cloud.githubusercontent.com/assets/6358545/9041347/943402c4-39ff-11e5-999b-3b5b560011fe.png)

**Comment by jsharkey13** [comment]
We've not seen this in two years, assuming it's either gone or fixed. Reopen if it reappears!
