### ISSUE TITLE
"Page not found" error

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#470]
a url such as: isaacphysics.org/events/anyrandomevent
gets a "Page not found" error

Is it possible to make any such url take one to the events page? I had thought that that was what would happen, or is it desirable to tell people that the url they've entered is not correct?

**Comment by sacummins** [comment]
I am not sure if this is what you mean but I think if a user enters an invalid or incorrect url they should be told in the form of an error message (as this is the behaviour for the rest of the site).

Is it currently showing this message for a valid event id as well as invalid one - if so then this is a bug.

**Comment by sacummins** [comment]
Closing as this seems to be behaving as expected.
