### ISSUE TITLE
Equation Editor Question Display

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#471]
For Symbolic Questions, when the equation editor opens it has the question text in a grey box
![image](https://cloud.githubusercontent.com/assets/8060558/9224572/48eee362-40fb-11e5-9086-c94a8ffc84d6.png)

but if more than one question is present on a page (either in a different accordion section as below, or else [breaking guidlines] in a different tab) then the text shown in the grey box is the question text from whichever question on the page is attempted first, and doesn't change no matter which part of the question (so a different symbolic question) is opened up into the editor.

The text then follows the user round the site; navigating to a new question page still gives the old question page first question text if a symbolic question exists on that page . . .

Issue on Chrome 44.

**Comment by jsharkey13** [comment]
A good page to see this on is: https://staging.isaacphysics.org/questions/test_equation_editor, though we've had problems loading pages with symbolic questions on after attempting them? It may or may not be related.

**Comment by daviesian** [comment]
Fixed in 1d773c72a38ae9e86b6da55e2d2e941560a61496.
