### ISSUE TITLE
Events becoming Past Events

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#473]
Can events be made past events more automatically than is current? I.e. __*after they finish*__ they should be greyed out and hidden from upcoming events (as they are now as soon as they begin) but also would it be possible to add:

* Automatically changing the `eventThumbnail`'s `src` attribute from the upcoming image to the past image (currently from `filename2.png` to `filename1.png` in all cases, though `filename` changes from event to event depending on type).

* Hiding the booking details by having a separate content block for them that is displayed only if it's before the event begins? We can then manually add the right stuff to this block, but it gets hidden automatically to save us having to go back and delete it manually after every event.

* Eventually, automatically incorporate attendance numbers into a block which is displayed after the event is over, along with manually added feedback?

**Comment by sacummins** [comment]
So I have added some logic (feedb090007cc5fd8bc689fac44bb2a34a3d3001) to add a grey filter over the top of any image when the event expires to reduce the need to have two images in the first place. It would be useful if you could modify the content to only use one picture. This is now live.

The conditional content block is a separate issue as once the new booking system comes in to play you would need to go through and remove them all from the content. I think for the time being it is probably better to still manually remove the book button, or simply make sure the eventbrite event prevents further bookings.

I am closing this issue for the time being. Please raise separate issues for events as they come up.
