### ISSUE TITLE
Mobile Site Functionality Issues - 3 related things

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#478]
The cookie message will not disappear on old versions of iOS, and this problem appears to be independent of browser (Chrome and Safari). The "I Agree" button flashes but doesn't disappear.
![image](https://cloud.githubusercontent.com/assets/8060558/9270783/4838fd5a-426c-11e5-9c5a-af83b98c877f.png)

----

The email verification warning overflows its bounding box and doesn't appear to wrap to screen:
![image](https://cloud.githubusercontent.com/assets/8060558/9270828/b1576d94-426c-11e5-85cb-50d8898db34f.png)

----

Chrome's autofill cannot autofill the login boxes on the latest iOS, and appears to type into a different box to the one displayed on-screen. If the user types into one of the autofilled boxes, bad things happen (cursor leaves box and types elsewhere on page, jumps around, and then finally the text appears to be in the box, but Isaac says no valid username or password has been entered) . . .

**Comment by alistairstead3408** [comment]
The email verification issue has been fixed for this. I can confirm the cookie message doesn't disappear in iOS6 on an iPhone 5.
