### ISSUE TITLE
Content Error Page - Menu Bar Number Incorrect

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#479]
On the page beneath the menu, it says 36 critical errors, but the menu bar says 30?

![image](https://cloud.githubusercontent.com/assets/8060558/9272413/0a4e610c-427a-11e5-8a7c-b2b0916b2689.png)

**Comment by sacummins** [comment]
I wonder if it is a caching issue. Could you check to see if it fixes when you refresh the page?

**Comment by jsharkey13** [comment]
It appears to be fine now; perhaps it was an odd caching issue. Do you want to close this?
