### ISSUE TITLE
Figures in tabs labelled in wrong order

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#483]
Issue found in content/concepts/physics/superposition.json by franksyvret.

Figures which are inside tabs appear to be titled last (when viewed on staging), resulting in titles which are not in numerical order down the page. Also evidenced in content/concepts/physics/kirchhoffs_laws.json

**Comment by jsharkey13** [comment]
Also happens if you have side by side figures and then a trailing figure:

![image](https://cloud.githubusercontent.com/assets/8060558/9735688/71555270-5634-11e5-8710-ebd60330c580.png)
