### ISSUE TITLE
Banner/Label/Watermark to denote Staging not Live site

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#486]
Could we add something distinctive to staging so it's clear which version of the site we're on. It's getting confusing with the regression test to ensure we're using the correct version of the site - they're all but identical except the URL and unpublished pages.

**Comment by alistairstead3408** [comment]
We have added a label to show when you aren't viewing a production version of the site.

**Comment by jsharkey13** [comment]
Do you know when this'll appear on Staging?

**Comment by alistairstead3408** [comment]
I think we'll be pushing to staging later today :-)
