### ISSUE TITLE
Equation Editor Single Symbol Answers

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#488]
If the answer to a question is a single symbol, say x, it's currently very hard (if not impossible) to get the equation editor to accept a single symbol as an answer . . . 

![image](https://cloud.githubusercontent.com/assets/8060558/9491983/75aa1cbe-4beb-11e5-8bdd-93d985fad54a.png)

The tick button does not display the symbol on its own to be selected as the answer.

**Comment by daviesian** [comment]
Fixed in 6969c2ec802596c75d0f5b8eb1d879830fafd63d.
