### ISSUE TITLE
Equation editor Issues on mobile

### ISSUE THREAD

**Issue by ss2165** [ucam-cl-dtg/isaac-app#491]
Nexus 5 Android 5.1.1 Google Chrome
Various issues, not particularly reproducible as each time the editor is opened something new is broken. Some examples:

Inability to pick different menu option (e.g. numbers) in portrait mode:
![image](https://cloud.githubusercontent.com/assets/12997250/9519305/62f00852-4cb5-11e5-8c32-7e31fc2c4806.png)

Upon rotating to landscape, options disappear:
![image](https://cloud.githubusercontent.com/assets/12997250/9519308/66c0171a-4cb5-11e5-93ec-fecee5adf59e.png)

On this question only the tick mark appeared: 
![image](https://cloud.githubusercontent.com/assets/12997250/9519310/6b085030-4cb5-11e5-98e0-e5d431771eb8.png)

**Comment by daviesian** [comment]
Replaced with #547.
