### ISSUE TITLE
Equation editor on mobile - unable to use

### ISSUE THREAD

**Issue by franksyvret** [ucam-cl-dtg/isaac-app#492]
Using Safari on iPhone 5c

Unable to bring up any numbers or symbols from tabs, tick button allows you to leave editor but is the only button which responds at all.

![image](https://cloud.githubusercontent.com/assets/13311336/9519347/d50451be-4cb5-11e5-8a99-12a531c20048.png)

**Comment by daviesian** [comment]
Should be fixed in fbf4af8aeb195f4ac9957fa9ca3cd7fc5b84461e.
