### ISSUE TITLE
Accordion layout formatting misbehaving?

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#503]
So the first accordion section has a tab in it at the bottom with quite a large margin on the left:
![accordion_section_1](https://cloud.githubusercontent.com/assets/8060558/9720387/79437f3e-5585-11e5-81f8-7f15ca9de865.png)
but _exactly the same JSON code as the first section_ when copied into any other section of an accoridon, gives:
![accordion_section_3](https://cloud.githubusercontent.com/assets/8060558/9720388/79454026-5585-11e5-9e9f-23a98cc5eda6.png)
with no large left margin in the tab.

Any ideas?

**Comment by daviesian** [comment]
Fixed in b631eb76be9fa903c300d298d4b0cf9b9358472f.
