### ISSUE TITLE
Additional clarity on Admin Stats page

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#506]
Could we edit the admin stats page so that it looks more like:
![image](https://cloud.githubusercontent.com/assets/8060558/9756977/b9f6a2da-56d5-11e5-8a25-9d468694612c.png)

where the circled line is added?

**Comment by sacummins** [comment]
Fixed in b8485dabd9a883d201d5d92abeb7d61dd395d31d
