### ISSUE TITLE
Maths in Question Exposition causes spurious newlines on Mobile

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#507]
Across all mobile devices and several browsers (Chrome/Safari) having a mathematical expression inside `$ ... $` causes a newline to appear in the question text on dev, staging and the live site:

![image](https://cloud.githubusercontent.com/assets/8060558/9765293/76281d32-570b-11e5-8d12-bca018e751eb.png)

**Comment by jsharkey13** [comment]
You can get the same behaviour on Chrome by resizing the screen:

![image](https://cloud.githubusercontent.com/assets/8060558/9765747/b132eb8a-570d-11e5-9d22-b9efe4ae2555.png)

but bizarrely the mouse stops working when I try, so it's hard to find a question where I don't need to open an accordion.

**Comment by jsharkey13** [comment]
It's even possible for this to cause scroll-bars to appear in the question boxes:

![image](https://cloud.githubusercontent.com/assets/8060558/9765937/7dc3e7b2-570e-11e5-8cda-2914f5c1712c.png)

**Comment by daviesian** [comment]
Fixed in 76085455031afca003045aaba14db9aadaf99fee.
