### ISSUE TITLE
School name with special character

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#508]
There's a school on the dropdown and school lists with an odd character in its name:

![image](https://cloud.githubusercontent.com/assets/8060558/9783793/e4268e16-579e-11e5-8346-fac123c85a44.png)

![image](https://cloud.githubusercontent.com/assets/8060558/9783737/86058828-579e-11e5-9a96-356d7a96c9d2.png)

but I've no idea how one would go about fixing it.

**Comment by sacummins** [comment]
This is an issue with the source data provided by the DfE. I shall soon be doing an update for this academic year so we can check to see if it is still broken.

**Comment by sacummins** [comment]
The school in question no longer exists in the DfE data so i believe this will be resolved next time the server is restarted and the new list is loaded.
