### ISSUE TITLE
Allow content creators to specify custom lists of symbols for symbolic questions.

### ISSUE THREAD

**Issue by daviesian** [ucam-cl-dtg/isaac-app#525]

**Comment by Morpheu5** [comment]
@daviesian has broken it, so he can close this when he fixes it.

**Comment by jsharkey13** [comment]
It says a comma separated list, but *actually* it's a `[space],[space]` separtated list where the two extra spaces are essential and yet really annoying. They find themselves all the way into the JSON where the list ends up like `x[space]`, `[space]y[space]`, `[space]z` (spaces replaced with `[space]` for clarity!) for no reason!! :(

**Comment by jsharkey13** [comment]
So this *was* a bug, but only because Ian had been splitting at `|` characters and so the cached version of the editor we had wasn't splitting at commas. Sigh . . .
