### ISSUE TITLE
Disaligned names in assignment progress

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#527]
We looked at this earlier on Alistair's computer but it was fine ?

![image](https://cloud.githubusercontent.com/assets/5931508/9794680/69d79e66-57e4-11e5-972e-e6f5b780dbec.png)

**Comment by mw141** [comment]
I had this for the last days too but thought it was deliberate??Mark W


Sent from my Samsung device

-------- Original message --------

**Comment by allydavies** [comment]
I saw it yesterday and the day before and put it down to the names being a but long.
Having cleared cache will check this this evening when I do the hangout.
Cheers
Ally
Mr Ally Davies
Hub Events Manager, Isaac Physics
Cavendish Laboratory
Cambridge University
J J Thomson Avenue
Cambridge
CB3 0HE
Tel: 01223 747036
Email: ally@isaacphysics.org
Twitter: @isaacphysics
Webpage: http://isaacphysics.org
On 10 Sep 2015 19:10, mw141 <notifications@github.com> wrote:
    
I had this for the last days too but thought it was deliberate??Mark W


Sent from my Samsung device

-------- Original message --------
