### ISSUE TITLE
Anvil apps in accordion causing crash

### ISSUE THREAD

**Issue by ss2165** [ucam-cl-dtg/isaac-app#531]
On this page, with two anvil graph sketching apps in individual accordions,
https://staging.isaacphysics.org/questions/graph_sketch_5_rational_1

page crashes once first app is loaded, unless second accordion is opened before it has finished loading (i,e, both apps load at the same time).

**Comment by dl495** [comment]
https://staging.isaacphysics.org/pages/graph_sketcher_beta also has this issue - also in tabs.

As a beta page for the graph sketcher it would be great to have more than one (or 4...?!) app in the same page.

**Comment by daviesian** [comment]
This is something to do with the anvil app itself. Enters an infinite loop if not displayed before the code starts executing, or something like that.

**Comment by daviesian** [comment]
The graph plotting code assumes an initial large (>52px) canvas, and hidden anvil apps have an initial size of 0. This causes it to go into an infinite loop.

I have fixed the infinite loop by faking the initial size of the canvas if necessary, but now the axes do not draw initially. Need to respond to the newAppHeight event somehow and draw them.
