### ISSUE TITLE
Random character in isaac prize draw dialog

### ISSUE THREAD

**Issue by alistairstead3408** [ucam-cl-dtg/isaac-app#533]
![isaac-questionnaire](https://cloud.githubusercontent.com/assets/810221/9871843/9aee9304-5b8d-11e5-8043-f75d96df2903.png)

**Comment by jsharkey13** [comment]
It looks like what happens when you take a Unicode string and interpret it as ASCII?

**Comment by alistairstead3408** [comment]
This now appears to work on live...

**Comment by jsharkey13** [comment]
I think it only ever affected some devices; it always looked ok for me.
