### ISSUE TITLE
teacher features icons/text when logged in as student

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#535]
When logged into a student account, I saw this view of the Teacher Features page:
![image](https://cloud.githubusercontent.com/assets/10402385/9881309/4895b6b6-5bc7-11e5-89bc-aec9b00fc7c5.png)
(does that work?)

The hexagons for setting assignments appear GREEN, when they should be grey (as they're not available until teacher status is granted).

Also, the text "Using isaac physics with your class" appears greyed out. The picture is correctly NOT greyed out, as this page IS accessible without teacher status, but the TEXT should also NOT be greyed out.

**Comment by jsharkey13** [comment]
Didn't we note this down at the meeting in the CL the Friday before last? Is it a cache thing, or is it not fixed?
