### ISSUE TITLE
Schools dropdown: duplicate entries

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#540]
Some schools have duplicate entries in the schools dropdown box.  This is because the school has more than on URN on the dfe database. 
This looks like it might be due to the school being assigned a new URN when it changes in some way, e.g. type of establishment changes, or age range changes. 
It could also be due to one establishment having more than one function e.g. Hill Road Sixth Form College is both a 16-19 college, and community school ie Adult Education Centre.

This means that one isaac students from one school will appear to be spread over two different schools.  

In the case of Hills Road the following corrections need to happen: 
TODO:
- for any students with URN 128383, change the code to 130615
- remove from the isaac database: URN 128383 

However, this is also the case for others - I'm not sure how many, but examples are:
Long Road URN 130616 and 128384 
Adams' Grammar School 123593 (Voluntary Aided School - no pupil numbers) and 137446 (Academy Converter) [ The school became an academy in 2011]

The dfe spreadsheet I have doesn't have postcode information.  With the postcode info it would be easy to identify which are duplicates.  We would then need to identify which one should be kept and remove the others from the isaac database.

**Comment by sacummins** [comment]
Relates to #548 .

This is actually as per the data provided by the DfE. So as far as we can tell all the schools suggested are valid.

If we start removing entries from the DfE data it will become quite a chore to manage next time we receive a database dump from them - which will overwrite our copy.

**Comment by hjp22** [comment]
In the Data provided by the DfE there is a status column which details whether the establishment is open, closed, open but proposed to close, or proposed to open.  
We need to display only the schools which are currently open i.e. open / open but proposed to close.  As far as I can tell this should remove any duplicates due to historical URNs.

**Comment by hjp22** [comment]
@jsharkey13 
Discussed with James. Agreed it should be possible to fix the duplicates.  Still have the problem that not all entries in the DfE data have postcodes, so not always possible for users to identify their school

**Comment by jsharkey13** [comment]
Fixed, see https://github.com/ucam-cl-dtg/isaac-app/issues/548
