### ISSUE TITLE
Browser window out of sync on local after server restart (when logged in). 

### ISSUE THREAD

**Issue by alistairstead3408** [ucam-cl-dtg/isaac-app#542]
1. Login on a local instance of the server
2. Restart the server
3. Refresh the page

![popup](https://cloud.githubusercontent.com/assets/810221/9989643/3c0302de-6052-11e5-9a99-98c76e557881.png)

**Comment by sacummins** [comment]
I have tried to reproduce locally and am unable to... I wonder if this only happens when the refresh occurs before the server is ready. i.e. the server returns a 500 or 404 to the user end point?

**Comment by jsharkey13** [comment]
We've not seen this in a while, and we all use Jetty now. It might be related to #643, but I think this issue is closable.
