### ISSUE TITLE
Number dragging "sticks" to mouse and won't drop.

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#543]
Order
Click on number (4) appears in hexagon and in white box.
Go to drag hexagon on to canvas - menu/toolbar disappears and number with it.
Hexagon and number then get stuck as mouse pointer but disappears when toolbar closes.

![image](https://cloud.githubusercontent.com/assets/5931508/9991406/8d7a5784-6061-11e5-8e3f-0f71774fd970.png)

**Comment by jsharkey13** [comment]
I'm fairly confident this is fixed on dev, but I might be wrong. It's an old bug reported before I think, #530 maybe?

**Comment by daviesian** [comment]
Indeed. Please re-open if it seems to persist.
