### ISSUE TITLE
Figure referencing (esp. on maths pages) broken again?

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#550]
Several things are wrong with figure references on staging again.

No references seem to work at all, not even ones that used to work fine (ones out of accordions, e.g. https://staging.isaacphysics.org/questions/lifeguard_num).

References on maths pages are purple, I don't know if they always have been, but I don't think they should be.
 ![image](https://cloud.githubusercontent.com/assets/8060558/10096195/7b143304-6367-11e5-8975-11d536bc75d8.png)
See, say, https://staging.isaacphysics.org/concepts/cm_graph_interpreting

---

I checked dev, but figures weren't even being numbered at all on there . . .

**Comment by daviesian** [comment]
This was a cache issue.
