### ISSUE TITLE
Maths Figure references wrong colour

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#553]
References on maths pages are purple, I don't know if they always have been, but I don't think they should be.
 ![image](https://cloud.githubusercontent.com/assets/8060558/10096195/7b143304-6367-11e5-8975-11d536bc75d8.png)

(Ignore the lack of number in the reference, I'm just reusing my image)

**Comment by daviesian** [comment]
Fixed in c0a80375aa7e78578e24e57ea41227766a11c29c.
