### ISSUE TITLE
Update account settings to deal with email

### ISSUE THREAD

**Issue by alistairstead3408** [ucam-cl-dtg/isaac-app#555]
It might be worth having tabs for email preferences and connections. 

![image](https://cloud.githubusercontent.com/assets/810221/10102943/37fdfc9e-6399-11e5-912b-6d004d3b228b.png)

**Comment by jsharkey13** [comment]
@alistairstead3408 This is now fixed, isn't it?

**Comment by alistairstead3408** [comment]
Yep :)
