### ISSUE TITLE
Subtleties of equation placements within editor

### ISSUE THREAD

**Issue by ljw21** [ucam-cl-dtg/isaac-app#556]
Couple of rendering issues with things that look vaguely sensible on the canvas not being recognised.
![image](https://cloud.githubusercontent.com/assets/5931508/10132443/659743c2-65ce-11e5-8480-a282d729ddf0.png)

![image](https://cloud.githubusercontent.com/assets/5931508/10132460/70bf7bac-65ce-11e5-9ea3-098b6ca0812e.png)

**Comment by jsharkey13** [comment]
I've been having problems with powers too (not tested latest version). It does recognise it if the power is much higher up though - well above the top of the letter `x`.

**Comment by ljw21** [comment]
![image](https://cloud.githubusercontent.com/assets/5931508/10132523/bcfd7f64-65ce-11e5-8252-8099a665164b.png)

![image](https://cloud.githubusercontent.com/assets/5931508/10132531/c6c70876-65ce-11e5-877c-f5bf99971e6c.png)

**Comment by allydavies** [comment]
I've had similar issues with squared symbol.
It also seems reluctant to read a minus sign at the start of an expression.
![image](https://cloud.githubusercontent.com/assets/10402385/10136886/c0bb12cc-65ee-11e5-8b1c-3a81970e5f29.png)


Here adding the minus sign seemed to make it read the squared symbol, but I tried several more times to get my minus sign to figure in the formula:
![image](https://cloud.githubusercontent.com/assets/10402385/10136926/ee8be1ae-65ee-11e5-8bae-58087a53abad.png)
![image](https://cloud.githubusercontent.com/assets/10402385/10136931/f8d2f954-65ee-11e5-9356-03943ed5c22d.png)
![image](https://cloud.githubusercontent.com/assets/10402385/10136935/fe939f9c-65ee-11e5-8761-f50f0c6e5143.png)

**Comment by jsharkey13** [comment]
Also, more than one symbol in a superscript doesn't seem to be accepted:
![image](https://cloud.githubusercontent.com/assets/8060558/10161681/a3192330-669d-11e5-99bc-1cd146b3e9b8.png)
though stacking superscripts seems to be fine, ironically:
![image](https://cloud.githubusercontent.com/assets/8060558/10161691/b734c7f2-669d-11e5-9479-6767831819c3.png)
but brackets does make it work:
![image](https://cloud.githubusercontent.com/assets/8060558/10161662/93ca34a0-669d-11e5-99d7-c995cf4c0d7d.png)

**Comment by daviesian** [comment]
Most of these are now improved. The last is still an issue.
