### ISSUE TITLE
Maths alignment issue with powers

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#559]
Symbols or units with powers in seem to be misaligned compared to their neighbours . . .

![image](https://cloud.githubusercontent.com/assets/8060558/10133385/c9ba1d56-65d4-11e5-9268-c79a1426f1dc.png)

on this question: https://staging.isaacphysics.org/questions/_regression_test_

But it's not everywhere: https://staging.isaacphysics.org/questions/escaping_the_earth :
![image](https://cloud.githubusercontent.com/assets/8060558/10133421/0eb2dae2-65d5-11e5-8f99-49f0eed4e488.png)
inside answers it seems to render just fine.

**Comment by daviesian** [comment]
This is a MathJax issue. When we get rid of MathJax, it will go away.
