### ISSUE TITLE
Multiple Choice and Symbolic questions not showing previously entered answer on page refresh

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#560]
![image](https://cloud.githubusercontent.com/assets/8060558/10133545/e3ca2960-65d5-11e5-938f-29d74caa8620.png)

and

![image](https://cloud.githubusercontent.com/assets/8060558/10133549/ee630ebe-65d5-11e5-85d4-82f8630702cd.png)

whereas for numeric questions:

![image](https://cloud.githubusercontent.com/assets/8060558/10133558/fe514386-65d5-11e5-865b-d6628a14d9f5.png)

though the accordion header bar doesn't get the answer shown on it as it does when you enter it correctly the first time.

**Comment by jsharkey13** [comment]
This could do with fixing before the equation editor beta goes live, though in #522 @daviesian says it does work, at least for symbolic questions. (The beta is on a `page`, and so perhaps can't work in the same way). I cleared my cache several times, and the page is definitely an `isaacQuestionPage`:

http://www.cl.cam.ac.uk/~ipd21/rutherford/scooter/app/#!/edit/master/content/beta_pages/_regression_test_.json

**Comment by ljw21** [comment]
This only happens if the symbolic questions is in an accordion.
