### ISSUE TITLE
Equation editor missing functions or functionality

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#567]
Equation editor is missing (in rough order of priority):

* `sec`, `cosec`, `cot`
* `sinh`, `cosh`, `tanh`, `sech`, `cosech`, `coth`
* `arcsin`, `arccos`, `arctan`, etc? This list could get very long; maybe we have an `arc` they can add to front?
* `>`, `>=`, `<`, `<=`
* `(  ,  ,  )` for coordinates?
* Column vector support?

**Comment by Morpheu5** [comment]
Hey, we have functions now...

**Comment by daviesian** [comment]
Let's re-evaluate with the new equation editor.
