### ISSUE TITLE
Centre-align markdown tables on page?

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#568]
Markdown tables right now look pretty odd:

![image](https://cloud.githubusercontent.com/assets/8060558/10169801/af749b32-66ca-11e5-93fd-d22d18372ef1.png)

they're left aligned but text can't flow beside them so they leave a lot of whitespace. In LaTeX, tables are usually set inside floating frames with a caption and are centre aligned - I doubt we want to go this far - but I think centre aligning would be an improvement.

Thoughts? (Please don't implement this until agreed this is best)

**Comment by daviesian** [comment]
Done in 39a9292098a4c39d734f6b4cdefc49a77316ba4b.

This will go live in the next release unless you ask us to revert the change. Please check all tables on the site!
