### ISSUE TITLE
Pod buttons not working on home page (touchscreen devices)

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#569]
The pods don't seem to be scrolling on the home page.  
Can this be fixed today?  I'm demo-ing the site tomorrow at a workshop and need show them how to navigate to the book.

**Comment by jsharkey13** [comment]
They work fine for everyone else, which is odd. It's not a caching issue; I don't know what else it might be.

No error is printed to the console, but the three pods which load on Heather's machine are the middle ones - not the same as everyone else; despite the green dot suggesting it's the first page of them . . .

**Comment by daviesian** [comment]
The carousel library that we use turns out to be insane. I suspect the buttons *will* work if you use your touch-screen to click them. That should give you a workaround until we find a proper fix.

**Comment by hjp22** [comment]
You're right - it works on the touchscreen but not on the mouse.

**Comment by jsharkey13** [comment]
These buttons are no longer present and the carousel library has been changed. I think we can assume that this is fixed now?
@hjp22 Could you try it out again when you get chance, and reopen this if it's still broken?
