### ISSUE TITLE
Answer Value Help pop-up under sig fig text

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#570]
Go to answer any question, click the ? on the right of the Value box.  An pop-up appears saying 'Here are some examples of numbers you can write'.
The text is pixelated:
![image](https://cloud.githubusercontent.com/assets/8695925/10277486/1907b5de-6b4e-11e5-9b49-26ef7fd0274e.png)

**Comment by jsharkey13** [comment]
The text isn't so much pixellated; the significant figures text in white underneath is displayed on top of it, causing it to appear odd.
