### ISSUE TITLE
Email address verification message - "Failed - token invalid or expired"

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#571]
User has just created an account and has emailed me the following:

Hi
 
Thanks for this – but...
 
When I register and then click on the verification email I get:
 
![image](https://cloud.githubusercontent.com/assets/10402385/10304486/6e8051dc-6c12-11e5-8550-0a98c3296db4.png)

 
 
This continues even if I request an additional email / new verification.
 
Help / suggestions???
 
Cheers
XXXX

**Comment by alistairstead3408** [comment]
Message was correct - token had already been used.

**Comment by jsharkey13** [comment]
Should it not perhaps tell users if they've already successfully verified their email address; rather than telling them to request yet another verification email?

**Comment by alistairstead3408** [comment]
It currently doesn't do this because verified accounts can re-use the verification process to change their email address, but I'll look at the error messages to make them a bit clearer.

**Comment by alistairstead3408** [comment]
Fixed in the api.
