### ISSUE TITLE
FilterWarnings allows long errors

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#574]
![image](https://cloud.githubusercontent.com/assets/8060558/10370531/4305d6e6-6dd7-11e5-8c3f-c83a90eb1c8f.png)
doesn't look the nicest, and whilst it does clearly show the user we can't do what they've asked, it might be nicer if it said

> There are no Chemical Physics, Circuits, Fields or Waves questions in level 6

or, more generally things like:

> There are no `x`, `y` or `z` questions in levels `i` or `j`
There are no `x` questions in level `k`

**Comment by daviesian** [comment]
Yes, it would be nice, but the text generation is already ludicrously complicated. It does what you ask for multiple levels, just not multiple topics.
