### ISSUE TITLE
B5 link opens B4 page

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#576]
Navigate to book -> B Mechanics
Click on 'view page' link for B5
B4 page opens instead of B5.

Also, in the B Mechanics modal, the B5 hexagon is a link  that returns to the B Mechanics page.  No other hexagon icons in the modal are links.

**Comment by jsharkey13** [comment]
I'm not sure if this mess of a page: `content/general_pages/book/chapter_content/ch_b.json` controls it or not. I'll try fixing it here . . .

**Comment by jsharkey13** [comment]
Should be fixed now! https://github.com/ucam-cl-dtg/rutherford-content/commit/ac327727d37ee2cff7cc00abe6cc9a50ff491eb0
