### ISSUE TITLE
Filter behaviour (only on Live) very definitely not as expected!

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#577]
Testing the live site this morning for the new content has made me notice a major, though puzzling, issue with the filter. Questions will show up as a board briefly, and then disappear - to be replaced by "No questions found in selected topics". Or adding another topic which alos has questions in the same level selected causes the board to go blank and again give the "No questions..." warning despite having shown questions just before another topic (with more valid questions) was added.

Repeatability is difficult; sometimes it works fine, other times it breaks for seemingly no reason . . .

**You'll almost certainly have lots of server error messages; you don't need to worry (too much)** - watching the Analytics data; nobody else is trying to view the questions because they don't know the new content exists yet. Though it seems to equally affect Fields as well as Circuits and Waves. We haven't been able to break it for Mechanics (i.e. the topics inside Mechanics - having Mechanics and Waves will break it sometimes) yet though . . .

None of these problems arise in any way on staging . . .

The console reports the same `500 (Internal Server Error)` each time:
![image](https://cloud.githubusercontent.com/assets/8060558/10509216/820169fe-7323-11e5-8bbc-ac43f8c87a23.png)
Unfortunately the `isaac.js` file it refers to only has one line of code: line 427, with 1.5 million characters . . .

**Comment by jsharkey13** [comment]
For instance, try loading `Waves` the field with no suptopics selected at `Level 2`. Wait for this to load and then add `Level 3`. It might break here. If it doesn't, choose `Wave Motion` the topic. If it doesn't break here, add `Superposition` the topic. This seems to do it every time.

**Comment by jsharkey13** [comment]
Also, I'm not sure the `500 (Internal Server Error)` GET request actually matches up with what's highlighted on the filter itself, but I can't tell any more because my console keeps filling up with errors :/

**Comment by jsharkey13** [comment]
Now there's `503 (Service Unavailable)` errors too :(

![image](https://cloud.githubusercontent.com/assets/8060558/10509803/256c876a-7327-11e5-8476-a8f3c6209aab.png)


This can't just have been me . . .

**Comment by daviesian** [comment]
Fixed by restarting Tomcat.

**Comment by jsharkey13** [comment]
Yep - definitely fixed!
