### ISSUE TITLE
Password confirmation

### ISSUE THREAD

**Issue by sacummins** [ucam-cl-dtg/isaac-app#579]
When a user changes their segue password on the my account page, they should be prompted to verify their current password before changes take effect.

This is to prevent a malicious user hijacking an account when a computer is left logged in and unattended.

**Comment by jsharkey13** [comment]
This has been done, probably with the new account setting page when it was released.

**Comment by jsharkey13** [comment]
This has sort of been done, actually. The old one isn't actually verified, which needs fixing.

**Comment by alistairstead3408** [comment]
Fixed here: https://github.com/ucam-cl-dtg/isaac-api/commit/0296a95c6532dff014672b47e744d256ef4763e2
