### ISSUE TITLE
Boards not loading properly on staging set assignments

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#586]
This bug only appears on staging, so it might be just a database issue.

If you click on set assignments, the buttons for adding a board from the book, top boards or create a board all appear, but your boards do not appear below them. The loading icon doesn't disappear and will remain as you navigate the site, until you refresh a page.

A similar thing happens if you go to my boards.

In both cases you get an "internal server error (500)"

**Comment by sacummins** [comment]
Fixed in api commit ucam-cl-dtg/isaac-api@731bd104481b89a00d249995b94252cc5474a225
