### ISSUE TITLE
Events page virtual events blank filter box

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#589]
The events page drop down box gets a funky blank item added when you use the url to show virtual events:
![image](https://cloud.githubusercontent.com/assets/8060558/10698660/0fdcfa90-79aa-11e5-835e-500a1b030112.png)

it should probably say "Hangouts"?

**Comment by mjc209** [comment]
I'd rather it said "Online Tutorials"
