### ISSUE TITLE
Account settings save button does not work after password autofilled

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#591]
If your browser autofills the password box on the account settings page without you realising (or you enter your current password in only one of the boxes) then make any other changes and save; the save (correctly) fails because passwords don't match. However, removing the password and trying to click save doesn't do anything, despite any other changes made. The warning stays displayed too:

![image](https://cloud.githubusercontent.com/assets/8060558/10731329/cd0835b4-7bec-11e5-85f7-889785fcfea6.png)

despite not trying to change the password at all.

**Comment by alistairstead3408** [comment]
User is now required to enter existing password before entering their new password (which is disabled until they type in the "current password" field - this problem should go away.
