### ISSUE TITLE
Online events should persist while they are ongoing

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#595]
Currently online events disappear from the upcoming events page as soon as their start time is reached - it would be useful for them to stay on the upcoming events page for another 30 minutes or so. Adding something to them to make it clear that they are live at that time would also be good.

These two things may work better if a finish time is added.

**Comment by jsharkey13** [comment]
https://github.com/ucam-cl-dtg/isaac-app/commit/1d725e9da0832682c85d29b2dfaf14c5e5b14ba4
https://github.com/ucam-cl-dtg/isaac-app/commit/0bdf4d9e66ff77001a2d2bb20313b8ace0d8ed35
See #655
