### ISSUE TITLE
Staging server emails go to same address as live emails

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#596]
System emails, such as the lock-out warning email, go to the same email address if from the live server as from the staging one. That means that when testing, I create several of these emails which look as if they were created by real users.

It would be useful if these emails could go to a different email address, perhaps something more like `staging-test@isaacphysics.org` instead?

**Comment by alistairstead3408** [comment]
Have requested staging-test@isaacphysics.org from @daviesian

**Comment by alistairstead3408** [comment]
With the new architecture we're looking to use this might not be practical to fix. Also @jsharkey13 has managed to redirect emails he triggers from staging to himself, so it's not a big problem anymore.
