### ISSUE TITLE
"x" close button on equation editor and going back on browser while using the editor

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#597]
I have just started experimenting with the equation editor and think that the following might deserve discussion:

When in the editor, the only easy way to leave the editor and return to the question page seems (to me at least) to be clicking on the green tick hexagon.  This is fine of course, but I think there is a "psychological" reason why users, particularly those not yet familiar with the site, would expect for there to be some sort of "x" close button which, when clicked, would take one back to the question page with an empty answer box.

Similarly, are we sure that users will like the fact that the browser "back" button currently leads not to the question page but to the page visited *before* the question page?

**Comment by daviesian** [comment]
Both good points. Created #714 and #715.
