### ISSUE TITLE
Eqn editor particularly demanding on Firefox?

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#601]
Inputting this expression seems to essentially incapacitate Firefox on my machine.  On James' Chrome the situation seemed a bit better but it still took almost a whole minute to recognize the expression.  
![capture](https://cloud.githubusercontent.com/assets/15194006/10847926/362a8c28-7f11-11e5-88ae-87ec3ef62863.PNG)

**Comment by daviesian** [comment]
This does not surprise me!

**Comment by Morpheu5** [comment]
Can we test this again with the new version?

**Comment by daviesian** [comment]
This was a parser issue. We don't have a parser any more. Problem solved ;-)
