### ISSUE TITLE
Tables can overflow pages

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#602]
Tables can overflow their page containers, and it doesn't look very nice:

![image](https://cloud.githubusercontent.com/assets/8060558/10884478/275d2244-8170-11e5-97fb-f7e9b8b12568.png)

would it be possible to bump down the font size for maths in tables to match that for maths (stuff inside $...$'s) outside tables? It seems much larger and appears to be 3 pixels taller at least on my screen.

**Comment by alistairstead3408** [comment]
We think the best way of dealing with this would be to provide a css class that you can add to the content that will override the font size to be smaller (e.g. <span class="mathjax-small">content</span>). Would you be happy with that?

**Comment by jsharkey13** [comment]
I think that would be the best way of dealing with it, yes!

**Comment by alistairstead3408** [comment]
Won't fix.
