### ISSUE TITLE
Easier adding of brackets and similar

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#605]
Several components like brackets, square root, or the modulus sign require you to enclose a bunch of symbols with them, and this is quite fiddly. I think it would be easier if you could instead select some symbols and then click to add a set of brackets around them.

**Comment by daviesian** [comment]
I like this idea a lot. I'll see what I can do.

**Comment by daviesian** [comment]
Not relevant to new equation editor.
