### ISSUE TITLE
Numeric Questions: "Significant Figures" warning takes precedence over "Known Wrong Answer"

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#611]
For numeric questions, the warning about significant figures takes precedence over any manually entered incorrect answer. This is the easiest way to program it, so it makes sense - but the commonest mistake for users doing early book questions and level 1 questions is to give the answer to the wrong number of sig figs.

It's overwhelmingly the majority of common wrong answers for these easy questions - and we have no way of explaining to a frustrated student what's going wrong if they don't really get sig figs and are new to the site. Ally and I have discussed this, and I tried adding a possible wrong answer to Section 6 on this page `content/general_pages/book/ch_a_p1.json` to explain what was wrong with the sig figs - but the message is never shown, instead overriden by a "Please give answer to correct sig figs" thing which won't help beginners.

I suggest this sig fig blanket warning being the fall-back, rather than the default - and manually entered wrong answer messages should always be displayed if they match the answer input, irrespective of sig fig . . . ?

**Comment by sacummins** [comment]
Closed in ucam-cl-dtg/isaac-api@e9fd85fde1614a13f33efe3589d5e25d91fdb57f
