### ISSUE TITLE
Quick Questions in Explanations format awfully . . .

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#613]
If you put a quick question in an explanation, bad things happen:

![image](https://cloud.githubusercontent.com/assets/8060558/11269865/058428e4-8eb2-11e5-9bd8-0c1532313ac0.png)

The text in the show/hide part of the answer is white on white (I've highlighted part of it to show that it is in fact there). **I take it this isn't something we want the functionality for anyhow?**

Try it in Part C here: https://staging.isaacphysics.org/questions/changing_perspective
and you'll need the correct answer as above.

**Comment by daviesian** [comment]
In answer to your **question in bold**: Correct ;-)
