### ISSUE TITLE
Multiple Choice questions correct answer not reloaded

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#615]
After answering a multiple choice question correctly, if you navigate away and back, or refresh the page - the correct answer isn't displayed; but the "Correct" text appears underneath.

This fix: https://github.com/ucam-cl-dtg/isaac-app/commit/83b6d3194c031eb75fa2906a587aef0e67c97f1f made it slightly better; before you couldn't re-select the correct answer without choosing a wrong one first. Now you can, but the info still isn't displayed on page load . . .

**Comment by alistairstead3408** [comment]
Fixed in 47e454269c5864150c39a93eb9fe6ce248e405a9

**Comment by jsharkey13** [comment]
Reverted and fixed again in https://github.com/ucam-cl-dtg/isaac-app/commit/2125d1a7d28dbbafaadeb7a23a84028c0a0d6e14
