### ISSUE TITLE
"Perfect" message (appearing when question has been completed) hidden in some cases

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#617]
![capture](https://cloud.githubusercontent.com/assets/15194006/11364280/476574b4-9297-11e5-9aa4-b26b6a7efa58.PNG)

Presumably it would happen analogously for other messages e.g. "In progress".  The issue is due to a longish question title so of course one could simply shorten this and other similarly long titles to avoid it.  However, perhaps another strategy would be to reposition these messages e.g. somewhere at the top (or top-right, top-left etc) of the hexagons instead.  Thoughts?

**Comment by alistairstead3408** [comment]
The lack of space available on the hexagons has always made things like this problematic. We *could* truncate the question titles but that might become confusing, and in the case above if "perfect" wasn't needed it would look quite nice. I think we probably just need to take a look at the styling and try to reduce the space between the topic and title if there's a progress message.

**Comment by jsharkey13** [comment]
I really don't think we can fix this; it used to be the case that titles had to be shorter than 3 lines anyway, so it was never a problem.

For instance `Series Internal Resistance` fits fine. I think this is a content issue instead (and I should have made it clearer in the wiki that titles mustn't be too long).
