### ISSUE TITLE
Sig figs engine misbehaving

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#618]
Here is the list of correct answers to a (published) question in Level 2 Circuits:
![capture1](https://cloud.githubusercontent.com/assets/15194006/11364976/73ad59c0-929b-11e5-9501-0c53adc719f4.PNG)
And here is staging accepting an answer with a wrong number of sig figs as correct
![capture](https://cloud.githubusercontent.com/assets/15194006/11364997/8c643da8-929b-11e5-8479-7fb957d31e18.PNG)

**Comment by jsharkey13** [comment]
This was introduced and noted in the most recent regression test (23/11/15). It's a trailing zeroes thing . . .

**Comment by sacummins** [comment]
This has occurred because the decision was taken to match against known answers first BEFORE we check for significant figures. The matching that occurs is numeric equivalence. And as 8.0 is equivalent to 8, it marks it as correct

**Comment by sacummins** [comment]
https://dev.isaacphysics.org/questions/a_diode_divider
