### ISSUE TITLE
Teacher Account requests - data gets lost

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#619]
When a user clicks on the the "Tell us you are teacher", they see on screen their name etc all appear in the contact form.
When the email arrives at this end (David, me etc), it JUST has their email address and everything else is missing.

Makes it a bit awkward to email them saying please also tell us... when we have no knowledge of their name even.

**Comment by jsharkey13** [comment]
This is somewhat urgent. It appears that the HTML `text/html` MIME part has only the email address in, which is what is displayed for Ally and David when it arrives - but the `text/plain` part contains the full detail required to actually respond to any of these emails. Ideally we want the HTML part to contain the full message, even if the plaintext part doesn't!

It would of course be best for all this to go through the ticketing system, but I'm still not convinced the `reply-to` stuff works properly . . .

**Comment by alistairstead3408** [comment]
This has been fixed on dev - the HTML part of the message should now be visible.
