### ISSUE TITLE
Deleting My Boards gameboards popup

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#622]
If you tick the "Prevent further dialogues" button, you cannot delete a board - and there's no indication or reminder of why not. You have to navigate away and back again; simply reloading isn't enough.

Probably a Chrome-specific issue!

![image](https://cloud.githubusercontent.com/assets/8060558/11445995/82ca5bf2-9529-11e5-8e96-09610929154b.png)

**Comment by sacummins** [comment]
This is browser specific behaviour. We can't do much about it unless we provide different popup infrastructure i.e. start using modals.

**Comment by alistairstead3408** [comment]
Browsers have this functionality so sites/developers can use it. If the users chooses to disable the functionality, they should expect not to be able to use the site as intended. Also, I can see people clicking this checkbox if the dialogues are annoying, but I think here, and everywhere else they are used, is justified.
