### ISSUE TITLE
Login Autofill on Mobile

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#625]
Chrome's autofill cannot autofill the login boxes on the latest iOS, and appears to type into a different box to the one displayed on-screen. If the user types into one of the autofilled boxes, bad things happen (cursor leaves box and types elsewhere on page, jumps around, and then finally the text appears to be in the box, but Isaac says no valid username or password has been entered) . . .

**Comment by jsharkey13** [comment]
If you type and delete a single character in both boxes, then it logs in just fine though . . .

**Comment by daviesian** [comment]
Now fixed.

**Comment by jsharkey13** [comment]
![photo-2018-01-05-15-32-19_7614](https://user-images.githubusercontent.com/8060558/34615930-67ffc352-f22e-11e7-91ea-1f5f020017ed.PNG)

Back to being broken again, but the same workaround still works . . .

**Comment by jsharkey13** [comment]
Fixed in https://github.com/ucam-cl-dtg/isaac-app/commit/3927794ad243a030c7daa60c0b23f1ea7cf76cc8
