### ISSUE TITLE
Can't unsubscribe from assignments emails

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#628]
This is a preview of the account settings page for a test account:
![image](https://cloud.githubusercontent.com/assets/8060558/11595039/514b7616-9aa5-11e5-87b0-febd81acd321.png)

and this is the email received for that test user upon assigning their group a gameboard:
![image](https://cloud.githubusercontent.com/assets/8060558/11595070/8b4a6d7c-9aa5-11e5-86ff-cb93ae25f15c.png)

despite having opted out long before a board being set.

Please confirm this isn't an artefact of the alias nature of these email accounts, but I think this bug may be serious enough to be an emergency change if real.

**Comment by daviesian** [comment]
Fixed.

**Comment by jsharkey13** [comment]
https://github.com/ucam-cl-dtg/isaac-api/commit/907cded71dc4c05dbad40fc930f98e1e99166cae
