### ISSUE TITLE
Group Welcome Email link text wrong for some cases

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#633]
If you join a group AFTER an assignment has been set, you get a group welcome email with a link to past assignments in it. The title of the gameboard link appears as "null" for this case:
![image](https://cloud.githubusercontent.com/assets/8060558/12239763/2335e16c-b882-11e5-8e19-e1c9078476da.png)

but the link works and points to the correct place. The gamebaord was not named by hadn ("Physics, Level 1" as assigned by the filter) but this shouldn't matter?

**Comment by alistairstead3408** [comment]
Fixed.
