### ISSUE TITLE
My Asignments doesn't show assigner name

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#635]
The My Assignments page doesn't show the assigner name, and all the server returns is the assigner ID. We don't really want to pass anything more than `[First Initial]. [Surname]`, but adding this is not simple to do . . .

**Comment by allydavies** [comment]
I think it's OK for no assigner info to be listed. Most students will have a small number of teacher connections and will have been told by their teacher about assignments the teacher has set.
I'd make this low priority, but later, yes nice to know who assigned it with first initial and surname.

**Comment by allydavies** [comment]
Could the assigner name be added to the email that accompanies each assignment?

**Comment by jsharkey13** [comment]
Now that there's a mentoring scheme and also prize draws etc, this has become increasingly important. It will require changes to the DTO to achieve though, and we'll want to be careful about what we give as the name. We want similar behaviour to the popup here: https://github.com/ucam-cl-dtg/isaac-app/blob/master/app/js/app/controllers/AccountSettingsPageControllers.js#L285 I think.

**Comment by Morpheu5** [comment]
We can only fetch the names when "setter" can set a board to the currently logged in user. This way, we

1. require users to be logged in, and
2. only fetch people they know anyway.

**Comment by jsharkey13** [comment]
This was fixed in https://github.com/ucam-cl-dtg/isaac-api/commit/5e31da2111de76ad229fcea4c9617f3fa17a1a83 turned out to already exist in the front end, but the display style was modified slightly for consistency in https://github.com/ucam-cl-dtg/isaac-app/commit/35a608f19a4f672d4ab9b279fc7ccad6dcd73526
