### ISSUE TITLE
Unnecessary vertical slider in graph sketcher pod on Firefox (100% zoom)

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#639]
![capture](https://cloud.githubusercontent.com/assets/15194006/12394829/234ebcd6-bdf6-11e5-8c16-29a5fff30a92.PNG)

**Comment by daviesian** [comment]
Is this still the case?

**Comment by ul208** [comment]
Seems to be, on both dev and staging.
