### ISSUE TITLE
0% turning into NaN% in Assignment Progress table

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#640]
The following steps appeare to cause a strange phenomenon in Firefox (and apparently not in Chrome) when using the test-teacher@test.com account:

1) Go to the Assignment Progress page

2) At the time of writing of this message, two groups were present: one empty and one with one student only (our test-student): clicking on the non-empty group called "test180116", and then on the assignment with the same name there, results in the following correct (I think) situation:
![capture](https://cloud.githubusercontent.com/assets/15194006/12395696/18417220-bdfb-11e5-8c2d-ceba0d1aa28a.PNG)
Note in particular the 0%s which are to be expected there

3) Now click on the other group (which happens to be empty), the page will be briefly refreshed and two assignments will appear as expected

4) Now click on one of the two assignments. This will result in another short page refresh as expected, but now the table for the *other* group will have been changed, with the 0%s being changed into "NaN%"s:
![capture1](https://cloud.githubusercontent.com/assets/15194006/12395810/b8a495ee-bdfb-11e5-8c9f-17ed6ded922d.PNG)

This appears to be an issue.

**Comment by alistairstead3408** [comment]
This was reproducible in the latest version of Firefox (43.0.1), but not in a slightly older version. It only seems to happen after clicking an assignment given to a group with no members. Will leave open to see if it's fixed in future version.

**Comment by jsharkey13** [comment]
This appears to have been fixed in https://github.com/ucam-cl-dtg/isaac-app/commit/4fc5d5f4c03fcd315d4394f8df11909c31865a8a along with a related bug whereby sometimes the titles/percentage bar didn't load at all.
