### ISSUE TITLE
Repeated "out of sync" error on new users after sign up

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#643]
At the teacher event today I noticed three teachers, two using Internet Explorer on (I think) Windows 8c and one using Safari on an iPad, experiencing the following problem: after registering as new users to the site, they would (correctly) be sent to the home page which would however then repeatedly show the "your session has changed"/"tab out of sync" message. Upon clicking "Continue", the same message would reappear after about 2 seconds.

In all cases I personally checked that only one tab was open. In the case of the iPad user, the problem certainly persisted after clicking on the email verification link. I don't know if that was also the case for the users on Windows.

In all cases, using Chrome (even on the iPad) solved the problem.

Unfortunately I was a bit pressed for time and couldn't collect more details (IE version etc).

**Comment by nh357** [comment]
This happened to me when logged in on Safari (9.1) using a private window. I logged out of all other sessions, but the out of sync message kept popping back up.

**Comment by daviesian** [comment]
Are we still seeing this issue a lot? It may well have gone with all the changes we made recently. Please re-open if it comes up again.
