### ISSUE TITLE
Federated account email change does not require provision of new password

### ISSUE THREAD

**Issue by alistairstead3408** [ucam-cl-dtg/isaac-app#647]
After registering with Facebook, Google or Twitter, if a user changes their email address, they cannot login using the new email address (because there is no password associated with account).

**Comment by daviesian** [comment]
I don't think this is a bug. If they've changed their email address, that means they want emails to go to a different address. It doesn't stop them logging in with the third-party provider does it?

**Comment by jsharkey13** [comment]
#883 would address the only real problem here!
