### ISSUE TITLE
Email template preview layout - bad spacing

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#651]
This is what the email looks like in the editor:
![image](https://cloud.githubusercontent.com/assets/8060558/12781367/de2916f6-ca6b-11e5-91cb-36909cd0522e.png)

But this is what it looks like in the preview:
![image](https://cloud.githubusercontent.com/assets/8060558/12781380/f8820620-ca6b-11e5-9ba8-c38e12ab534f.png)

And this is what it looks like when it arrives:
![image](https://cloud.githubusercontent.com/assets/8060558/12781353/c2b152a8-ca6b-11e5-91eb-cd6745f631a6.png)

The spacing is wrong in the pre-sending preview; it confused me quite a bit!

**Comment by alistairstead3408** [comment]
Fixed in https://github.com/ucam-cl-dtg/isaac-api/commit/8c1cfc6309ba401e8959b3396549e9ba34bc865d
