### ISSUE TITLE
Simulations not loading on Safari 

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#652]
The simulations don't load on Safari 9.0.3 (latest version). I only get a thin bar and a loading symbol. 
This is from https://staging.isaacphysics.org/questions/balancing_forces_on_electron_sim
<img width="938" alt="balancing forces simulation" src="https://cloud.githubusercontent.com/assets/5849827/12813351/679bb344-cb2f-11e5-9c95-1c15c3835a35.png">

**Comment by daviesian** [comment]
I've moved this to our Anvil issue tracker.
