### ISSUE TITLE
Can't delete users on local testing versions `Access-Control-Allow-Origin` error

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#657]
`XMLHttpRequest cannot load http://localhost:8080/isaac-api/api/admin/users/5. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.`

I have no idea what's causing this nor why, it might not really be a bug as such?

**Comment by alistairstead3408** [comment]
Just tested this locally and worked fine. Not sure what's going on with your local version...

**Comment by jsharkey13** [comment]
This is a Jetty thing we think; it works fine for @alistairstead3408 because he doesn't use the Jetty stuff. 

It's an API thing, almost certainly involving the `jetty-local-cors-filters.xml` config apparently.

**Comment by daviesian** [comment]
Hopefully fixed in https://github.com/ucam-cl-dtg/isaac-api/commit/9a5bd6c3f5973efe4e103f92d5d492d1094fa62d.
