### ISSUE TITLE
Top Boards page gone, but still linked to

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#658]
It's linked to on `/set_assignments`
![image](https://cloud.githubusercontent.com/assets/8060558/13007793/86cb3fd0-d18a-11e5-8749-f40e66a3f21c.png)

----
and also in the modal on `/groups#isaacModal` (invite users to a group)
![image](https://cloud.githubusercontent.com/assets/8060558/13007820/9e90e4da-d18a-11e5-807c-e34547c5bb6a.png)
----

How do we fix this? Get rid of the link, or bring back a simple top_boards table somewhere?

**Comment by daviesian** [comment]
I'm happy with Alistair's "temporary" fix ;-)

**Comment by alistairstead3408** [comment]
It was a great fix :P
