### ISSUE TITLE
General Pages background not white

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#660]
The background of general pages is transparent where their content is not in an accordion. Given the weird background on the site, this can make the text over it hard to read:
![image](https://cloud.githubusercontent.com/assets/8060558/13084061/aaaa2144-d4cf-11e5-803d-e4be8f3c73a6.png)

**Comment by daviesian** [comment]
I *think* this is by design. It doesn't make things that hard to read - see https://isaacphysics.org/privacy.

If we were going to change it, we'd need to audit every general page that might be affected, which I'm not hugely enthusiastic about doing.
