### ISSUE TITLE
Symbolic Questions "Correct" or "Incorrect" status not reloaded.

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#661]
Whilst old answers are saved, the "Correct" or "Incorrect" text is not - neither is the feedback, though this is less essential . . .

**Comment by jsharkey13** [comment]
Actually, it turns out this depends if you're navigating directly to the page, or if you're coming from another page. If it's a direct navigation (or hard-refresh of the current page) the "Correct"/"Incorrect" message *is* properly loaded.

Any other way of reaching the page and it is not.

**Comment by alistairstead3408** [comment]
Fixed.
