### ISSUE TITLE
Preserve Group Tokens on Sign Up

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#664]
There is an easy work around for this issue which I'll state here and email around to all on the project.

When we (or teachers) ask/invite a student to join a class group, the pop-up does not appear iff the student needs to create an account. i.e.

Student A has no account and clicks the group code link. S/he's not logged in so the register / sign in page appears. A registers. The popup never appears, unless A clicks on the link again.

Student B has an account but isn't logged in. S/he clicks the link, signs in, the pop-up appears.

My current work around is ALWAYS tell the students the steps in the following order:
1. Create account - https://isaacphysics.org/register (or log in if you have an account already).
2. Click the link to join the group. Click yes on the pop-up. (Make sure pop-ups aren't blocked in the browser settings.)
3. Look in my assignments - https://isaacphysics.org/assignments

This may not need fixing, or be impossible to fix. No problem if that's the case, just close the issue, as I'll email the reading group list telling all how to do it. I'll also add text on the teaching with Isaac page to state the correct order.

**Comment by daviesian** [comment]
This is definitely fixable, if slightly tricky. Stick with your workaround for now and we'll look into it.

**Comment by jsharkey13** [comment]
This is becoming an increasing headache, especially with events; Lisa and I had to deal with half a dozen confused students before some events. Preserving the URL param through registration and possible 3rd party callbacks is the hard part - we could use session storage, but this token is a security thing (and sometimes we can't write to local storage anyway: #603 ).

**Comment by jsharkey13** [comment]
LocalStorage seems the best bet. There exists a helper service to do this already in [`Persistence.js`](https://github.com/ucam-cl-dtg/isaac-app/blob/master/app/js/app/services/Persistence.js), see [`GameboardController.js`](https://github.com/ucam-cl-dtg/isaac-app/blob/master/app/js/app/controllers/GameBoardsControllers.js#L41) for a working example.

**Comment by jsharkey13** [comment]
I think this is now fixed. Please reopen if you see issues!
