### ISSUE TITLE
Links to specific accordion sections only work partially in Firefox (Windows and Mac)

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#670]
I have noticed that, when following a link to a specific accordion section in Firefox for Windows or Mac, the page is correctly opened and so is the relevant accordion section, but one is not automatically taken to the beginning of the accordion section.  To see an example, click on the link to "gravitational potentials" in the preamble of https://isaacphysics.org/concepts/cp_fields .

**Comment by jsharkey13** [comment]
This turned out to be a Firefox thing; for some reason most browsers allow `$("body").animate(...)` but Firefox does not. To support Firefox as well, it needs to be `$("html,body").animate(...)` which risks running it twice on browsers that support both body and html scrolling - but oh well!
