### ISSUE TITLE
Virtual Workshop - message box flickering

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#674]
Event:  isaacphysics.org/events/27042016_virt_vectors
Viewed in Chrome:Version 49.0.2623.112 m

Section: Send message to tutor:  
constantly tries to resize - switches between 'Your previous messages:' appearing on one line, and 'messages' appearing on a new line.  When it tries to put 'messages' on a new line, a scroll bar appears on the right hand side of the 'Send a message to the tutor' section.  Switches between the two views many times each second.

**Comment by jsharkey13** [comment]
I can't reproduce this, and I had (until it updated just now) the same Chrome version. It coped fine with the page being resized. It's an Anvil app Michael made, so I'm not sure there's much we can do about it unless it's an Anvil issue.

**Comment by daviesian** [comment]
Please reopen if this is still a problem. Works for me too.
