### ISSUE TITLE
Invisible Gameboard Hexagons!

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#678]
Firefox (44 and 45) only. Not an issue on staging, but an issue on test and dev.

![image](https://cloud.githubusercontent.com/assets/8060558/14635741/b004f0e8-061f-11e6-9302-adbe99f245c5.png)

Caused by an svg filter not being found. Problem in both Chrome and Firefox, but Chrome fails safe and doesn't try applying a filter, Firefox applies a blank filter, thus rendering everything invisible!

Seems to be a location thing: the filter ought to be found at `test.isaacphysics.org/gameboards.html#filter1', but this is interpreted as a gameboard hash perhaps? Especially since it doesn't contain the `.html` part in the actual browser request.

Disabling the filters by hand leads to the same thing Chrome shows; all hexagons the same colour:
![image](https://cloud.githubusercontent.com/assets/8060558/14636001/db87f354-0620-11e6-9959-a0c8ae094961.png)

**Comment by jsharkey13** [comment]
Also affects Safari. Same workaround that fixes Firefox (manually disabling filters) works too.

**Comment by nh357** [comment]
The hexagons have disappeared again on the live site on Safari version 9.1 (latest one). Fine on Chrome and Firefox.

**Comment by nh357** [comment]
The error message that comes up in safari is:
Failed to load resource: the server responded with a status of 401 (Unauthorised) - https://isaacphysics.org/api/v1.7.1/api/users/current_user

**Comment by jsharkey13** [comment]
So it seems the only way to fix this is to ditch the SVG filters entirely. It had got to the stage where IE was the only browser correctly applying all the layers and filtering (they were meant to be slightly stripey, as texture, and all different colours).

Using CSS alone it's possible to replicate the different colours, but impossible to replicate the patterned stripey nature. I think we can live without that. The pure CSS solution will always work in all browsers and will be a permanent fix.

The following JSFiddle will help making any new colours: https://jsfiddle.net/isaacphysics/summf41z/4/
