### ISSUE TITLE
Events manager should be able to demote teachers

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#685]
At events we sometimes have to elevate 20+ users to teachers (who may be from diff schools).
It is possible to make an error doing this and give the wrong user a teacher account. It would be good to be able to demote such a user immediately. Currently we'd have to email Lisa, James or David (I think?) to ask them to demote the user on their admin account.

I'm using Win 10 on dell i7 laptop, chrome v 49.0.2623.112 m

**Comment by jsharkey13** [comment]
So far as I can tell, the "Demote" box on the User Manager page works fine to demote teachers already? It works for me as an event manager or as an admin.

It will fail on Content Editors or higher, but works fine for promoting/demoting teachers and students.

![image](https://cloud.githubusercontent.com/assets/8060558/14953056/ca816968-105d-11e6-8746-b43fa056cac0.png)
You might need to refresh the page the first time after clicking the button. This is a known bug with the code that we use to make buttons, and we don't know how to fix it.
