### ISSUE TITLE
Events manager would benefit from some degree of wild card search

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#687]
Before the role of events manager was created, it was possible for Heather and me to elevate teachers at events using the wild card search for names, so we'd start typing palfreyman Pal and hit search. For understandable reasons of good security the wild card search has never been available for the role of event manager.

However, there are often cases where it's a real nuisance - e.g. a long and/or unusual name being called out to you esp if with a strong accent. And the only way we can find the user is by typing the name in full perfectly.
Some examples:
Aniereobi
Arunathevan
Sathiyamoorthy

Would be good if e.g. wild card only worked with min 3 or 4 characters (that would still give very little chance of large data insecurity).

**Comment by jsharkey13** [comment]
So this is on its way. I'll let you know the syntax and stuff when it's gone live and I see you next. It's not what you expect, irritatingly.
