### ISSUE TITLE
Generate MathML and improve LaTeX output

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#691]
There are lots of spurious spaces in generated LaTeX expressions (especially after fractions) and occasionally some missing, like after minus signs.

Would also be good if the syntax tree could output MathML too, to be put onto the scope; but if possible not sent back to the server as it used to be (it's not needed, and really long inside the stored JSON!)

**Comment by Morpheu5** [comment]
I'm removing spaces, but can you make tests for these?
