### ISSUE TITLE
Question filter default from have a go

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#702]
A user clicking on 'have a go' 'choose your own questions' gets the filter open looking like this:
![image](https://cloud.githubusercontent.com/assets/10402385/15327289/d72c125c-1c48-11e6-9752-b4763994f816.png)
It's not obvious that it's a filter from this view.

This view is better, but also hides the further filters that can be applied
![image](https://cloud.githubusercontent.com/assets/10402385/15327225/9ae74c3a-1c48-11e6-884d-48033e528ec8.png)

IMHO this would be perfect
![image](https://cloud.githubusercontent.com/assets/10402385/15327373/25b03566-1c49-11e6-8652-34b0c1a6bde2.png)
as clicking any of the terms in the lower line will expand that, so the behaviour is immediately obvious.

**Comment by jsharkey13** [comment]
I can't reproduce this at all, and the middle image is the behaviour that we see when loading the site for the first time. I don't think there's anything else we can do about this.
