### ISSUE TITLE
Caching Issues with API version number in URL

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#705]
When we update, the old API number is in the Angular code cached on people's machines. When we update the version and turn off the old API, the Angular still sends all its requests to this URL. This leads to lots of errors for users.

Do we leave the old one up for a day to allow easing onto the new version? Can we ensure that people don't received cached versions of specific files? It shouldn't be an issue if people actually click the refresh button because the server should say the file has changed?

**Comment by daviesian** [comment]
I think we should leave the old version up for a day, yes. That should be enough to solve most of it. It would be nice if we could force index.html to *never* be cached, but I don't think I've succeeded just yet. Anyway, leaving the old version up for a while should solve most of the problems.
