### ISSUE TITLE
Wrong icons on teacher page in Safari

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#706]
I discovered that the icons on the hexagons in the teacher page at isaacphysics.org/teacher_features don't display properly in Safari 9.1.1.

This is in Safari:
[teacher page Safari.pdf](https://github.com/ucam-cl-dtg/isaac-app/files/283769/teacher.page.Safari.pdf)

This is in Chrome, as it should be:
[Teacher page Chrome.pdf](https://github.com/ucam-cl-dtg/isaac-app/files/283770/Teacher.page.Chrome.pdf)

**Comment by jsharkey13** [comment]
This is a bug with Safari still not supporting SVG images properly. I knew this was an issue when I built it, but it's become more of an issue now Chrome on iOS uses Safari to render stuff.

We could wait for Safari to support SVGs properly (or I'll see if I can find some propriety equivalent of what I'm doing), or else I'd have to rewrite the page. It's quite neat right now.

**Comment by daviesian** [comment]
We'll wait for Safari to catch up with the rest of us.
