### ISSUE TITLE
Surname search with 3 letters in role manager

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#707]
I tried searching for a user whose surname was only 3 letters long on the role manager page. I got the error:
"User Search Failed
You do not have permission to do wildcard searches with less than 4 characters."

Luckily I had their email address, but it would be useful to be able to search for people who have only 3 characters in their surname, if that is all we have. It could be combined with their first name, if the issue it would bring up too many people.

**Comment by jsharkey13** [comment]
I made it so you can just search for short surnames; that wasn't the problem, it was if you had wildcards in there than less than 4 chars was bad. But now it check you're using wildcards before stopping you :)
