### ISSUE TITLE
Some SVGs not properly rendered on Chrome (but OK on e.g. Firefox)

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#709]
As described in the title, screenshots below with comparison between Firefox 46.0.1 (left) and Chrome 51.0.2704.63 m (right) output.

From /concepts/cp_gauss_law:
![capture1](https://cloud.githubusercontent.com/assets/15194006/15717102/602895e6-281d-11e6-94b8-a7b8787fe785.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15194006/15717101/60281a3a-281d-11e6-80f7-e38ab6985915.PNG)

From /concepts/cp_fields:
![capture3](https://cloud.githubusercontent.com/assets/15194006/15717108/6d1bfd92-281d-11e6-9040-53d67b9405dc.PNG)

**Comment by jsharkey13** [comment]
I'm afraid this isn't an app issue; it's a content issue. I recall this happening before with some SVGs made in Inkscape when something odd had been done to their arrows. Unfortunately I don't remember if there was a fix aside from redrawing the arrows in the affected files (nor what caused the issue in the first place). Perhaps @mjc209 might remember what we did?

**Comment by ul208** [comment]
After some research, I think what's described here http://stackoverflow.com/questions/28298441/arrows-in-svg-arent-rotated-when-rendered-by-browsers is probably the reason this is happening.  A solution is also explained there and I'm proceeding to edit the figures accordingly. @mjc209 might be interested to know about this too.  I'll close this issue as soon as I can confirm that this strategy works.

**Comment by ul208** [comment]
So yes, the answer by user John Nagle in that Stackoverflow question contains an implicit fix for this issue. I will write it in the Wiki.
