### ISSUE TITLE
Can't select "None" as units option for Numeric Qs

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#731]
Selecting "None" as the option for numeric questions leads to the server sending back a "You did not provide any units" response unless "Require Units" is set to false - but if it's set to false, there's no box to choose units anyway.

We feel this used to work; what has changed? If nothing has - can we make it work?

**Comment by mjc209** [comment]
I believe this was changed here: https://github.com/ucam-cl-dtg/rutherford-content/issues/246 when it really shouldn't have been

**Comment by mjc209** [comment]
Oops, no, that's a really old issue, sorry.

**Comment by mjc209** [comment]
The earliest complaint I've received about this bug is from Friday, if that's of any help. We've had lots of complaints about this one over the weekend.

**Comment by jsharkey13** [comment]
Ok, so it worked fine in `v1.7.7` but not in `v1.8.0-2` - so as you say it was introduced very recently. And it's nothing to do with the back end. Perhaps it's Angular 1.5 being silly with `''` vs `null` and treating them the same?
