### ISSUE TITLE
Equation editor misses out on Python sign * for multiplication if after a square root

### ISSUE THREAD

**Issue by ul208** [ucam-cl-dtg/isaac-app#737]
@rh584 has just identified the following bug in the equation editor: when constructing an expression of the form (in this order) sqrt(x) times y, the resulting Python according to the editor is `sqrt(x)y` and not `sqrt(x)*y`.  On the other hand, placing y before sqrt(x) produces the correct `y*sqrt(x)`. This means that all sorts of correct answers will be marked as incorrect.  It also means that we might have to revise all symbolic questions involving sqrt and correct the Python on editor.isaacphysics.org where appropriate.

**Comment by jsharkey13** [comment]
This will have no practical effect, because in the `equality-checker` code, `sqrt(a)*b` is treated identically to `sqrt(a)b`. However, for neatness, it should be fixed.
