### ISSUE TITLE
Symbols don't originally appear in the chemistry editor on Safari

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#746]
The symbols in the chemistry equation editor don't appear when you first open it. It is only once you have clicked on all of the tabs, that the symbols actually appear. The numbers are there from the start. This only happens the very first time you load the chemistry equation editor.
[chem editor.pdf](https://github.com/ucam-cl-dtg/isaac-app/files/497724/chem.editor.pdf)

**Comment by jsharkey13** [comment]
This appears to be a `z-index` issue, that somehow resolves itself when the 4th tab is opened. Weird that it should only affect Safari!
