### ISSUE TITLE
Map for events

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#750]
It would be a great help for users to be able to see all our upcoming events on a map (ideally where the markers for events would act as links to the booking page, or where they provided other data about the event when one moused over or clicked on the marker).

**Comment by jsharkey13** [comment]
So this is both straightforward but also very hard. It's easy to add a map to the events page, and populate it with icons that tell you all about the event when clicked. What's hard is getting the position of the event from the postcode - given that we have postcode, it seems silly to ask for lat and long when we already have functionality to go from one to the other. 

It's just that accessing that functionality and caching it correctly is hard. I'd need to talk to Ian or Steve about the balance between expanding the location service to augment events with lat/long values based on their postcodes, and just adding lat/long to the events themselves and requiring them to be specified in the content editor . . .

**Comment by jsharkey13** [comment]
![image](https://cloud.githubusercontent.com/assets/8060558/20223633/686324b6-a832-11e6-923a-d22aa2a9fecd.png)
This was relatively simple to add, but it only shows events if we already know the lat/long of the postcode (i.e. we have looked up its location before because there's an Isaac school there). This is true for maybe half the events; I'd need to change the code quite dramatically to avoid taking forever to load if we didn't already have the location and had to send off a request to look it up . . .

**Comment by jsharkey13** [comment]
Add this to `events_page.html`:
```html
  <ui-gmap-google-map center='map.center' zoom='map.zoom' ng-if="locations.length != 0">
      <ui-gmap-markers models="locations" coords="'self'" icon="'icon'" events="map.markersEvents">
      </ui-gmap-markers>
      <ui-gmap-window show="map.window.show" coords="map.window.model" options="map.window.options" closeclick="map.window.closeClick()">
        <div>
          <h3><a href="/events/{{eventPopup.id}}" target="_blank">{{eventPopup.title}}</a></h3>
          {{eventPopup.subtitle}}<br>
          <b>When:  </b><time datetime="{{eventPopup.date | date:'yyyy-MM-dd H:mm'}}">{{eventPopup.date | date : 'EEE d MMM yyyy'}}</time><br>
          <b>Location:  </b>{{eventPopup.location.addressLine1}}{{eventPopup.location.town ? ", "+eventPopup.location.town : ""}}<br>
          <div ng-if="eventPopup.status == 'OPEN'"><b>Places: </b>{{eventPopup.numberOfPlaces - eventPopup.numberOfConfirmedBookings}}<br></div>
          <a href="/events/{{eventPopup.id}}" target="_blank"><b>View Full Details</b></a>
         </div>
      </ui-gmap-window>
  </ui-gmap-google-map>
```
and add this to `EventsController.js`:
```javascript
$scope.eventPopup = {};

$scope.map = {
    center: {latitude: 54.5, longitude: -2},
    zoom: 5,
    markersEvents: {
        click: function(marker, eventName, model, args) {
            $scope.map.window.model = model;
            $scope.eventPopup = model;
            $scope.map.window.show = true;
        }
    },
    window: {
        marker:{},
        show: false,
        closeClick: function() {this.show = false;},
        options: {}
    }
};
$scope.locations = [];

$scope.loadMap = function() {
    api.eventOverview.get({"limit":-1, "startIndex": 0, "showActiveOnly": showActiveOnly}).$promise.then(function(result) {
        $scope.locations = result.results;
    });
}
```
and call `loadMap()` from a sensible place (like in `loadMore()`), and voila! But it only shows maybe half the events, which is a tad problematic :P

**Comment by jsharkey13** [comment]
So this has been added, and we're just accepting that lat/long's will be manually entered in the content editor.

See https://github.com/ucam-cl-dtg/isaac-app/commit/7bad319d3600486c6d253b44bb23623be462ee37
and https://github.com/ucam-cl-dtg/isaac-api/commit/a21234ca33d68f62ae00db2b8f3e377724ff7bdb
