### ISSUE TITLE
Add Irish Schools to school name list in dropdown

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#754]
We are working with the Irish education department. They want to promote use of isaacphysics.org in Irish schools.
We have a list of all Irish secondary schools. It would be helpful to have this added to the DfE list of English (and some Welsh) schools.

Related to issue #548

**Comment by jsharkey13** [comment]
This has been done, but may require modification when users start actually entering schools. We should keep an ear open to feedback on how easily Irish teachers and students find their school.
