### ISSUE TITLE
Duplication of boards in Set Assignments?

### ISSUE THREAD

**Issue by mjc209** [ucam-cl-dtg/isaac-app#755]
I seem to have the same board appearing twice in set assignments (this is the research@isaacphysics.org account). Not sure if this is a recurring problem:

![image](https://cloud.githubusercontent.com/assets/6358545/20962239/783d192c-bc60-11e6-9d2c-a876b18fb208.png)

**Comment by mjc209** [comment]
It's worth noting that these are definitely the same board as when I assign a group to one instance, it also appears on the other instance

**Comment by jsharkey13** [comment]
So I'm pretty confident this is just the list of boards changing between page load and "Load more" being clicked. The server has had a new board added to the top of its list, but the client doesn't know about this. So it asks for boards 6-12 and gets the 6th-become-7th board twice.

It's perfectly correct behaviour from the server, but I agree the front end might do something smart like hide the duplicate.
