### ISSUE TITLE
Log User Role Change

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#807]
We should definitely log when a user's role changes to the logged events table, probably with key `USER_ROLE_CHANGE`. We may want to use this information to follow up new teacher accounts and that sort of thing, so it may be sensible to store a `teacher_since` field in the user object too?

Both things could be straightforwardly added to the [`UserAccountManager`](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/api/managers/UserAccountManager.java#L739-L748). We'd need to check that you couldn't set the field yourself if we added it to the user object.

**Comment by allydavies** [comment]
teacher since field sounds excellent - will be useful for tracking longitudinal behaviour

**Comment by jsharkey13** [comment]
We do now log `USER_ROLE_CHANGE` at the very least, as of https://github.com/ucam-cl-dtg/isaac-api/commit/84dd7210957832380037c4ba056ed571e614797e, though it's now called `CHANGE_USER_ROLE` since it belongs to the admin user (see https://github.com/ucam-cl-dtg/isaac-api/commit/955af185fb4554dcd1e1f3a94064dc87c50f7944).
