### ISSUE TITLE
csv download - improve appearance

### ISSUE THREAD

**Issue by allydavies** [ucam-cl-dtg/isaac-app#810]
The current csv download gives headings for **each** column that include redundant info, though it might be useful to include that info somewhere in the heading info.
This makes is difficult for some users to see which column is which.
There are often teachers in our intro sessions who are rather inexpert at using excel (wrap text, align text vertically etc; don't know what I mean when I refer to clicking in the cell and looking at the 'formula bar'; they find it hard to read the info at the end of the string in the cell)
See snip:
can't upload at the moment

Some suggested options:
1. reverse the order of the title so it would appear
"G1.1 - G1 Kelvin Scale of Temperature" rather than as currently
"G1 Kelvin Scale of Temperature - G1.1"

2. make the column headings just e.g. G1.1, G1.2, and include the assignment info "G1 Kelvin Scale of Temperature" in what opens as row 2 or 3 of the file (in excel)

An ideal view might be something like this:
can't upload at the moment - have saved snips for later

**Comment by allydavies** [comment]
![image](https://cloud.githubusercontent.com/assets/10402385/23551065/4be2902e-000c-11e7-9f74-cbde582071a3.png)


![image](https://cloud.githubusercontent.com/assets/10402385/23551075/5ae1c3ba-000c-11e7-910a-e83b4ddb524c.png)

**Comment by Morpheu5** [comment]
This https://github.com/ucam-cl-dtg/isaac-api/commit/7c7df367b849fcd2e2869d11c023277c21c252ea addresses this issue by reversing the order of question part and question page titles.
