### ISSUE TITLE
Postgres Connection Pool AutoCommit True?

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#814]
We use in an `org.apache.commons.dbcp.BasicDataSource` in [`PostgrSqlDb.java`](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/database/PostgresSqlDb.java) as the database manager, which creates a connection pool.
We don't explicitly configure it, but I think we have auto-commit set to true, so we don't have to do transactions ourselves. However, some places in the API [set auto-commit to false explicitly](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/dos/PgEmailPreferenceManager.java#L188), and then [set it back to true](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/dos/PgEmailPreferenceManager.java#L205) before finishing with the connection. If an exception occurs, then the auto-commit true part isn't called.

If there's a connection pool, we may inadvertently leave auto-commit false on these exception-interrupted connections. It may be that the try-with-resources Java block calling close on the connection is enough to remove it from the pool, or maybe there isn't even a pool. I don't know enough about Java and can't find where to look.

The newest version of the `BasicDataSource` library (see [here](https://commons.apache.org/proper/commons-dbcp/api-2.1.1/index.html)) has a function `setEnableAutoCommitOnReturn(...)` which allows auto-commit true to be set on each connection returned to the pool for safety. Someone with some knowledge of Java should look at this and we should decide about upgrading the library.

**Comment by jsharkey13** [comment]
Though out of date, [this](http://stackoverflow.com/questions/520585/connection-pooling-options-with-jdbc-dbcp-vs-c3p0) and [this](https://www.slideshare.net/psteitz/apachecon2014-pooldbcp) seem relevant.

I'm trying just upgrading and will put the code on an issue branch for someone who knows better how JDBC works to review ( @sacummins ).

**Comment by jsharkey13** [comment]
The code on that branch worked fine for a few days on my local version; but I can't easily test concurrent load, nor do I fully understand all the configuration.

**Comment by sacummins** [comment]
It appears that setEnableAutoCommitOnReturn defaults to true in the version we are using so this should be fine. https://commons.apache.org/proper/commons-dbcp/apidocs/org/apache/commons/dbcp2/BasicDataSource.html#setEnableAutoCommitOnReturn-boolean-

**Comment by jsharkey13** [comment]
(The referenced commit hadn't yet been merged; reopening until it has.)
