### ISSUE TITLE
Unnecessary Errors in Logs (Unpublished Content on Content Error Page)

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#834]
We're seeing hundreds of error messages in the logs about once a day, of the form:
```
[ERROR] GitContentManager:150 - Failed to locate the content .......
[ERROR] GitContentManager:150 - Failed to locate the content .......
[ERROR] GitContentManager:150 - Failed to locate the content .......
[ERROR] GitContentManager:150 - Failed to locate the content .......
[ERROR] GitContentManager:150 - Failed to locate the content .......
```
all batched together. I've managed to narrow down the cause of the problem to this line in the [`AdminFacade`](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/api/AdminFacade.java#L562), where the content errors page is populated. The page (importantly and usefully) checks for successful ingestion of content by attempting to load it by ID. This fails for unpublished content and so we see the error messages in the logs.

In moving to the new system whereby *all* content is indexed, and only *the API itself* filters unpublished stuff; we have lost some things from the old system (where elasticsearch only had published content and errors were calculated from this):
 * **Referential integrity**: if a piece of content referes to an unpublished piece of content, there is no way we can currently detect this. Before, the live site at least would add it as a warning.
* **True indexing failures**: if content with a given ID doesn't exist on the live site, it's not clear if this is an index failure or if the content is merely unpublished.

**Comment by daviesian** [comment]
All fixed in ucam-cl-dtg/isaac-api@7e6ef8341d33b1fef673e9c11f02a22380d1b54a.
