### ISSUE TITLE
Unpublished Units Appear on Live Site

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#843]
The list of units used globally by numeric questions on the staging and live sites is identical:
https://staging.isaacphysics.org/api/any/api/content/units
https://isaacphysics.org/api/any/api/content/units
(it may need sorting to demonstrate it clearly, but they are).

I think this is because the list is generated and added to elasticsearch separately now - and I think the cause of the problem is exactly the same as #834. Michael spotted some biology units on the live site, and copying the two results above into Python quickly proved it.

I imagine a fix involving two sets of unit indicies and content errors will fix both issues.

**Comment by jsharkey13** [comment]
It can (and is) being mitigated by a content change to take advantage of `availableUnits`, but it still should be fixed!

**Comment by daviesian** [comment]
Fixed in ucam-cl-dtg/isaac-api@284ff2d6616790048d6fe8cc49fa89b7ced20e4d
