### ISSUE TITLE
NullPointerExceptions if emailEventDetails is Null on Event Booking

### ISSUE THREAD

**Issue by jsharkey13** [ucam-cl-dtg/isaac-app#856]
If `emailEventDetails` is null, it cannot be added to an immutable map (for instance [here](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/isaac/api/managers/EventBookingManager.java#L531)).

This could be tricky to fix, but can be avoided for now.

**Comment by sacummins** [comment]
Fixed in ucam-cl-dtg/isaac-api@0f6e8ede23b16592383ef6db65d7490a1bffbd26
