### ISSUE TITLE
Various Event Management Bug fixes and feature changes

### ISSUE THREAD

**Issue by sacummins** [ucam-cl-dtg/isaac-app#862]
1. Isaac to remember which event you were on after logging in. I think this is done in one other place, but I can’t remember where.
2. Contact us at the bottom of the email: Heather is happy for it to remain as it is, but would it be possible to pre-populate the Message Subject in the form with the date and location of the event? That would allow us to know which event they were contacting us about.
3. Change text below contact us form. Waiting for Ally to confirm wording.
4. I’ve just noticed a change of wording on the form that Ally requested. Can “Emergency Telephone Number” be changed to Emergency Contact Phone Number”, please? That avoids any ambiguity and should still fit on the form.
5. Add explanations to Dietary requirements: e.g. Severe allergies, carry epipen, prone to fainting fits
 and accessibility: e.g. Wheelchair access, hearing impairment, visual impairment.

**Comment by sacummins** [comment]
1. Done in 7aacec8f12e4147ab778b3cbc697e20f8db2c6c3
2. This will take a bit longer as the contact us page does not accept parameters yet. We can change it but I think this is separate issue.
3. Lisa and I have agreed new text under the events form.
4. We have put a separate emergency contact section in 7aacec8f12e4147ab778b3cbc697e20f8db2c6c3
5. Tooltips added for the extra info fields to illustrate what we want.

**Comment by jsharkey13** [comment]
The contact form does already allow customisation of the subject line, if you direct people to `/contact?subject=Your Subject Here` it will work - so I presume a `<a ui-sref="contact({"subject": "Your Subject Here"})">` might also work . . .

**Comment by nh357** [comment]
Thanks Steve. There was also change time in the confirmation email. It gives the time an hour early. And to also remove the PM. 

Thanks

**Comment by sacummins** [comment]
Closing and creating a new issue for number 2
