### ISSUE TITLE
Waiting List not working correctly for Events

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#872]
Test Event 29th September 2017 
https://staging.isaacphysics.org/events/29092017testevent
Capacity: 1
logged in as student1: ***@gmail.com – booked 1 place 
logged in as student2: ***@cam.ac.uk: FULL – Waiting list is available
-	tried booking a place on the waiting list: ERROR Event Booking Failed 
logged in as event manager: ***@isaacphysics.org
-	student1 is successfully booked on workshop
-	student2 is successfully on the waiting list

**Comment by mlt47** [comment]
I have implemented the fix, just needs a release.

**Comment by jsharkey13** [comment]
We think this is fixed by https://github.com/ucam-cl-dtg/isaac-api/commit/891213458fcb7eff46084298dfc90d133777591f
