### ISSUE TITLE
Problem with My Assignments to-do list

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#878]
The 'Assignments To Do' list shows assignments set within the last 4 weeks.

For student workshops we create the event on isaac and set the assignments at least 6 weeks before the workshop date, sometimes up to a year in advance.  If a student books a place on the workshop more than 4 weeks after the event was created then the assignment won't appear in the 'Assignments to do' list, but will be in 'Older Assignments'.  

This problem will also exist for teachers who set boards for a term in advance.  

Solution:  Have a 'Complete By' date for assignments.  Assignments appear in the To Do column until the Complete By date has passed. Then they are moved to 'Older Assignments'.

**Comment by sacummins** [comment]
Addressed in ucam-cl-dtg/isaac-api@f4141f1ebde7f7a0777f7620c077abf51935a47a when merged API PR#113

**Comment by jsharkey13** [comment]
I had to remove this functionality from the pull request following discussion in our technical meeting: https://github.com/ucam-cl-dtg/isaac-app/commit/4589dc5d6606f727ab19ec33e49d6b815cb51135
