### ISSUE TITLE
Events: Student can book onto Teacher event

### ISSUE THREAD

**Issue by hjp22** [ucam-cl-dtg/isaac-app#894]
If a student account tries to book onto a teacher event, they have to select their School Year Group from a dropdown box.  Options are: Year 9 / 10 / 11 / 12 / 13 / NA-Teacher / NA-Other.

They should only be able to book onto the event if they select NA-Teacher or NA-Other. 
ie. if they select Year9-13 they are declaring they are a student and so shouldn't be able to book onto a teacher event.

**Comment by sacummins** [comment]
I thought students shouldn't be able to book on to these at all? Should I just hide the form if they are not registered as a student?

**Comment by jsharkey13** [comment]
This was an explicit feature requested by the events team: https://github.com/ucam-cl-dtg/isaac-api/commit/b4394ab34009add0d4b7a5db5c2db5c9024b0fad

**Comment by sacummins** [comment]
Closing as conflicting request
