### ISSUE TITLE
Investigating possible race condition problems when starting API with Kafka

### ISSUE THREAD

**Issue by dunderwood88** [ucam-cl-dtg/isaac-app#905]
In some instances upon starting the API we get the following exception:

`org.apache.kafka.common.errors.BrokerNotAvailableException: Error choosing node for listTopics: no node found.`

Another example:

`Error in custom provider, org.apache.kafka.streams.errors.StreamsException: There are no partitions available for topic streamsapp_site_stats-v1.42-localstore_user_data-changelog when initializing globalstore globalstore_user_data`

These seem a little vague, and restarting the API seems to clear away problems, but it would be nice to deal with this possible race condition.

**Comment by jsharkey13** [comment]
No more Kafka, no more problem!
