### ISSUE TITLE
Cannot place cursor within a written equation in beta equation editor to correct text

### ISSUE THREAD

**Issue by nh357** [ucam-cl-dtg/isaac-app#926]
When using the beta equation editor, where you can write your answer, if you spot a mistake after writing your answer, or close brackets in sqrt(), you can't place the cursor where you like, or within the brackets. The cursor always appears at the end of the string. It would be nice if you could place the cursor where you wanted so that you can easily fix mistakes.

**Comment by jsharkey13** [comment]
Works absolutely fine in Chrome on Windows. Which browser and OS is this?

**Comment by jsharkey13** [comment]
Fixed by https://github.com/ucam-cl-dtg/isaac-app/commit/f3a4da2b047b675a70183886fa3b13bb01a9bd70
