### ISSUE TITLE
Enable sharing of group data between multiple teachers

### ISSUE THREAD

**Issue by sacummins** [ucam-cl-dtg/isaac-app#927]
## Assumptions 

- The data sharing model must be preserved - i.e. only direct user action from the data owner (i.e. user account to which the data is attached) can result in data being shared with a third party.

## Workflow changes and definitions
- Teachers should be able to create a group (thereby becoming the **owner** of the group). 
- **Owners** should be able to maintain a list of **additional managers**
-  **Additional Managers** are other **teacher users** who can view the members of the group and their associated marks providing the individual users have granted them permission.
- **Additional Managers** will be able to see the group as if it were there own within the assignment progress page.
- **Additional Managers** will be able to see the group in their group management page but it will not have a group delete or edit group managers button.

### Differences between owners and additional managers
- Both owners and managers can edit the group name and archive the group
- Both owners and managers can access the group invitation link so that they can share it with students
- Both owners and managers can remove students from a group
- Both owners and managers can set assignments to a group
- Only Owners can delete a group
- Only Owners can manage the list of additional managers for this group
- Only the original assignment setter can delete an assignment

### Example 1: Teacher creates a group and immediately adds additional managers before issuing the group token to students.

In this case students when using the token will be presented with the list of users whom they are sharing there data with. 

If they press 'ok' the student will be added to the group and all teachers currently listed in the additional manager list (plus the owner) will be granted access. 

Individuals from this list can still be revoked in the my account page.

### Example 2: Teacher creates a group and issues a token to students. Later they subsequently add an additional manager 

**Sub case 1:** Students have already granted permission to the newly added additional manager - No action required from students. - E.g. if the newly additional manager has already separately set homework.

**Sub Case 2:** Students have NOT already granted permission to the newly added additional manager - Students will have to take action by reusing the group token to grant the missing teachers permission. This can be done via the account settings page or via the link shared by teachers.

## Removing additional managers from a group
The owner teacher will be able to remove additional managers from the group - this will only have the effect of removing the group from the additional managers list of groups and their ability to set assignments to the group. 

It will have no impact to student permissions granted to the teacher.

**Comment by sacummins** [comment]
What do you (@allydavies @hjp22 @ljw21 @jsharkey13) all think of the above. This is what I have implemented already but any modifications should be discussed here.

**Comment by allydavies** [comment]
Seems sensible to me.
One question relating to teachers moving on - we've been asked this kind of thing:
Is there any way to pass on 'ownership' of a group? Suppose teacher A creates the group and adds B (class teacher) and C (head of dept) as additional managers. Teacher A moves school, whilst the group of students is still to be taught by B and maybe now D. Can A pass ownership to B so that B can add D?

**Comment by sacummins** [comment]
@allydavies I will raise another separate ticket for managing group owners as I think in the short term an admin can just do this on request.

**Comment by jsharkey13** [comment]
Andy raises a good question:
I own a group and add a cover teacher, A, to the additional managers. They set an assignment, and then leave and I remove them from additional managers. I then want to remove this assignment, but I can't. Neither can the cover teacher un-assign it, without being re-added.

I think group owners should be able to un-set assignments to their groups too, but maybe this is sufficiently niche it can be added later?

The release plan is a soft launch next release, with only the team able to use it. If it works for us, a few releases later, we'll allow any teacher to opt-in via Beta Features. Then by the start of August, we'll deploy it for all teachers to meet our targets for September and the next academic year.

**Comment by sacummins** [comment]
I think the whole interaction between assignments and groups needs thinking about. I suggest we raise another ticket for managing assignments and what happens if a student is no longer in a group but has still completed the assignments.
